### ISSUE TITLE
TGM class with WordPress 3.9

### ISSUE THREAD

**Issue by profteam** [TGMPA/TGM-Plugin-Activation#191]
Hello ... I just updated my WordPress to 3.9 but unfortunately the TGM messages are not working , when I deactivated a plugin nothing happens and no messages displayed. Moreover; it is working fine with 3.8

Any help regarding this? Is there an update soon?

**Comment by GaryJones** [comment]
Did it work for 4.0? 4.1?

**Comment by jrfnl** [comment]
Closing due to lack of feedback. Also tested on 3.9 myself and found no issues.
