### ISSUE TITLE
TGM Activation activates incorrect plugin and will not allow it to be de-activated

### ISSUE THREAD

**Issue by mcheck** [TGMPA/TGM-Plugin-Activation#198]
tgm plugin activation required plugins mistakenly activates SOD QB Connector instead of Woocommerce.  

SOD QuickBooks Connector for Woocommerce:
http://sixtyonedesigns.com/

Perhaps there is something in the plugin that needs to be updated in terms of registering itself with wordpress and woocommerce?

With themes that use the TGM plugin Activation to require the use of plugins, in this case, specifically Woocommerce, the activation process THINKS SOD QB Connector is woocommerce and automatically activates it.

It will not allow it to be de-activated.

If I remove the SOD QB Connector, and activate a theme that requires Woocommerce, it will correctly activate Woocommerce plugin.  And it allows me to properly de-activate woocommerce if need be.

Can someone suggest a way to determine (and fix) why QB Connector plugin might be telling the system that it IS woocommerce?  Perhaps it is registering itself in an old way, or needs to call something different?

This behavior is on a completely bare wordpress install that has only woocommerce and the SOD QB POS connector plugin installed.

I know this is off topic considering TGM Plugin Activation is only the symptom that pointed me in the right direction, and I have contacted the respective theme and plugin developers through normal channels but I get a lot of finger pointing.

So I would like to either:
* Fix the plugin as to not confuse itself to be activated when calling woocommerce OR
* Disable the automatic plugin activation

Thanks much for any help.

**Comment by GaryJones** [comment]
What's the plugin slug for the SOD Quickbooks Connect for Woocommerce?

**Comment by jrfnl** [comment]
Closing due to lack of feedback.
