### ISSUE TITLE
Issue with Piklist Checker and TGM

### ISSUE THREAD

**Issue by Tidal-Wave** [TGMPA/TGM-Plugin-Activation#264]
Im pretty sure this is an issue with Piklist Checker and not TGM, but I figured I would post here also to make you aware.

When attempting to use both the piklist checker (v0.6.0) and current version of TGMPA, one or the other seems to be injecting extra tags into the warnings.

Here is a picture of what it looks like: http://i.imgur.com/OtKpSz8.png
Here is a picture of the code: http://i.imgur.com/VP1tl4E.png

Im not sure which is at fault, but I assume it is piklist because it the link is to the themes page where as TGMPA would link to plugins or it’s install mechanism.

I am also [posting this to the support forum for piklist](https://piklist.com/support/topic/piklist-checker-tgm-plugin-activation-causes-extra-links/) so the authors are aware of the issue.

**Comment by GaryJones** [comment]
Which extra tags?

**Comment by Tidal-Wave** [comment]
I have the <a> tag highlighted in the second picture. See how it wraps your nags "this theme requires..." In the first picture, that shouldn't be like that.

**Comment by GaryJones** [comment]
OK, I see that.

Which version of TGMPA are you using?
There was a recent change (though I think unrelated, cc @jrfnl) or at least a PR regarding settings notices.

**Comment by Tidal-Wave** [comment]
According to the Comments in the TGM file 2.4.0, but I pulled for this particular project back in late Nov. or early Dec. so it looks like I may be slightly behind, but I don't think that the PRs I missed related to screen_icon matter in this case. 

Like I said, I think its on piklists side, but I wanted to make this team aware incase it came up. I will probably switch to just using TGM to include piklist. They suggest to use their checker plugin, but I'm only using it for metaboxes, so its not critical that it be installed. Cripples some fancy theme features, but not the theme itself.

**Comment by GaryJones** [comment]
Closing on the assumption that this is on piklists side.
