### ISSUE TITLE
Split into PSR-4 compatible class files

### ISSUE THREAD

**Issue by GaryJones** [TGMPA/TGM-Plugin-Activation#265]
Instead of one big file, I'd like to see the project split into multiple files, with each class having their own file. Project should be structured to support PSR-4 autoloading that comes with Composer, with a manual set of requires as a fallback if the `vendor/autoload.php` file isn't present (@Rarst: any issue with doing this?).

Smaller files will make the code easier to follow and maintain.

**Comment by Rarst** [comment]
That would work just fine.

**Comment by GaryJones** [comment]
Thanks @Rarst.

**Comment by vpratfr** [comment]
+1000 on this one (even if not PSR-4 compliant, just splitting into a few files would be a huge improvement and make contributing a lot easier)

**Comment by jrfnl** [comment]
@vpratfr Is included in the planning for v3 - coming soon

**Comment by vpratfr** [comment]
Great news, let me know if I can help.

**Comment by cullylarson** [comment]
+1

**Comment by tlartaud** [comment]
Up :)
