### ISSUE TITLE
Allow bundled version of TGMPA to bootstrap install of wp.org TGMPA plugin

### ISSUE THREAD

**Issue by GaryJones** [TGMPA/TGM-Plugin-Activation#273]
Paraphrased from George Stephanis (https://twitter.com/daljo628/status/570966415974359041):
1. Create a plugin version of TGMPA, and put it into the wordpress.org plugin repo.
2. Have v3 of TGMPA automatically recommend that users install the TGMPA plugin from wp.org repo. 

This means the TGMPA code is updatable, so long as we keep backcompat. Loading it as a plugin, also means it loads before and theme-bundled version of TGMPA library too.

**Comment by georgestephanis** [comment]
:+1:
