### ISSUE TITLE
installing TGM-Plugin-Activation

### ISSUE THREAD

**Issue by donkrug** [TGMPA/TGM-Plugin-Activation#277]
Can someone give some really specific examples on how to install TGM-Plugin-Activation, please?

I understand using the functions.php file but what does the second part mean:

Open your theme's functions.php file and 

"use the require_once() function to, well, require the class file (once) in your theme."

require_once dirname( __FILE__ ) . '/class-tgm-plugin-activation.php';
 
add_action( 'tgmpa_register', 'mytheme_require_plugins' );
 
What is (__FILE__) suppose to be?

how do you do this?

I also do not understand

"Create a function to configure TGM Plugin Activation and hook it to tgmpa_register via the add_action() function."

thanks

**Comment by mdshaffi** [comment]
Use the following code in functions.php to add the functionality


// Activate Default Plugin
if (file_exists(get_template_directory().'/zapper-framework/tgm-plugin-activation/example.php')){
        require_once( get_template_directory().'/zapper-framework/tgm-plugin-activation/example.php' );

**Comment by donkrug** [comment]
I will give it a go and report back. Thanks.

**Comment by jrfnl** [comment]
Closing due to lack of feedback.
