### ISSUE TITLE
Remove GET, POST and REQUEST superglobals usage

### ISSUE THREAD

**Issue by GaryJones** [TGMPA/TGM-Plugin-Activation#287]
There's very few instances that `REQUEST` superglobal should be used - it can be changed to a `GET`.

Overall though, I'd like to see the use of these superglobals change to used `filter_input()`. This provides implicit `isset()` checks, and filtering too. This will help to pass the [WPCS VIP sniff](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/VIP/SuperGlobalInputUsageSniff.php) warning, as well as giving cleaner code.

**Comment by jrfnl** [comment]
+1 with one caveat: I've found through work on another plugin that there are unfortunately servers out there which have the Filter extension disabled/where PHP is compiled without Filter, so it cannot be always relied upon and you *need* a fallback for when Filter is not available or need to make it a requirement for use of TGMPA (and therefore for use of all themes/plugins which use TGMPA).

For inspiration:
https://github.com/Yoast/wordpress-seo/blob/trunk/inc/class-wpseo-utils.php#L301-L448
https://github.com/Yoast/wordpress-seo/blob/577cbad1a52f454d25588a71f46f2e0ce42a7cc4/inc/class-wpseo-utils.php#L676-L727

**Comment by GaryJones** [comment]
Useful, thanks.

I'm wondering why there isn't a WP core `wp_filter_input()` wrapper that basically does the function in that second link.

**Comment by jrfnl** [comment]
> Since there's a few functions needed, it seems like a good candidate for a standalone library class.

or maybe better even: a good candidate for a WP core patch ?

**Comment by jrfnl** [comment]
> I'm wondering why there isn't a WP core wp_filter_input() wrapper that basically does the function in that second link.

And yeah, but then I wonder about quite a lot of things in core.... Using the INTL extension instance could greatly improve a number of things, same with FILTER.

Oh and regarding the code in the second link - there are a number of issues with that code - such as using constants from an extension which was just determined to not be available -, but the idea is good (just not the actual code).

**Comment by jrfnl** [comment]
I'm pretty sure that where needed this was addressed in #368. Close ?
