### ISSUE TITLE
Error message "One of the plugins is invalid"

### ISSUE THREAD

**Issue by ryanlabelle** [TGMPA/TGM-Plugin-Activation#343]
Seeing a new error message when I bulk activate. All plugins get activated correctly but this error message pops up.

Tested on 2.4.1 and 2.5.0-alpha

![screenshot](http://new.tinygrab.com/6407caa59e35e1c0c60949c3eb579642ed3c3fac80.png)

**Comment by jrfnl** [comment]
@ryanlabelle That message does not come from TGMPA, but from WP core. I need more information to figure out what's going on.

**Comment by ryanlabelle** [comment]
Thanks. I'll have a closer look at the log files / debugging.

**Comment by hatra-e** [comment]
I got this message once, when the packaged plugin was not in the source folder.

**Comment by ryanlabelle** [comment]
Thanks. I'll check that although I'm pretty sure all plugins are in the source folder. I checked out the logs as well but nothing.

**Comment by jrfnl** [comment]
Any more info ? Could it be that the plugin is not packaged according to the WP standards, i.e. all files and subdirectories in a directory named `plugin-slug` ?

**Comment by ryanlabelle** [comment]
I think I fixed this from the suggestion of @hatra-e - I double checked folder names and the folder structure before I zipped. All seems good now.

Plugins should be in a folder and then zipped. I believe the folder should be the same name as the plugin file (main plugin code).

**Comment by jrfnl** [comment]
> Plugins should be in a folder and then zipped.

Correct.

> I believe the folder should be the same name as the plugin file (main plugin code).

That's a good rule of thumb, but not necessary. WP will look through the .php files in the root of the folder to find the one which contains the plugin headers and regard that one as the main file. I don't remember by hart what the order is in which it does the checks, so can't say at this moment which would be the most optimized.

Can we close this issue as resolved ?

**Comment by ryanlabelle** [comment]
Yes please. We are all good here.
