### ISSUE TITLE
object(WP_Error)#422

### ISSUE THREAD

**Issue by digisavvy** [TGMPA/TGM-Plugin-Activation#398]
I get an error when clicking "install" for one plugin in the repo. The offending plugin: https://wordpress.org/plugins/webmaster-user-role/. When trying to install using TGMPA, the below error shoots out after. Screen: http://recordit.co/UCfSAiQYnN

Other plugins have worked fine. So I'm pretty sure it's a repo issue, but would like another set of eyes/opinions on this.
```
object(WP_Error)#422 (2) { ["errors"]=> array(1) { ["plugins_api_failed"]=> array(1) { [0]=> string(219) "An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums." } } ["error_data"]=> array(1) { ["plugins_api_failed"]=> string(2) "N;" } }
Something went wrong with the plugin API.
```

**Comment by jrfnl** [comment]
@digisavvy What version of TGMPA are you using ? with what version of WP ? Single or multisite ?
And what are the settings with which you've registered the plugin with TGMPA ?

**Comment by GaryJones** [comment]
Closing due to lack of feedback.
