### ISSUE TITLE
WordPress 4.2.2

### ISSUE THREAD

**Issue by bstump** [TGMPA/TGM-Plugin-Activation#400]
I updated a site to WP 4.2.2 and now the TGM plugin isn't working. Is anyone else having this issue? Not seeing a thread, perhaps it's a PEBKAC or ID10T error.

**Comment by jrfnl** [comment]
@bstump "not working" is not something anyone can try to reproduce. Please write up a proper bug report and make sure you include the following:
* what version of TGMPA you are using
* which plugin or theme on your install is including TGMPA and if you are the maintainer of the plugin or theme, any relevant settings
* what version of WP (ok - you mentioned that 4.2.2)
* a good description of the problem you are experiencing
* steps you took so we can try to reproduce the issue

I just tested (again) on WP 4.2.2 and can find no issue, so unless you can provide us with more detailed information, I'll be closing the issue.

**Comment by bstump** [comment]
Apologies, I should have given more information.

- I'm using the latest version of TGMPA, 2.4.2.
- This is my own theme, no settings or anything were changed, I simply upgraded WP to 4.2.2.
- WP Version 4.2.2.
- The problem is as described, it's simply not working. When I login to the backend, nothing comes up asking me to install plugins, activate plugins, etc.
- I upgraded a 4.2.1 WP install to 4.2.2. No plugins changed or anything.

**Comment by bstump** [comment]
I will check again on my end to see what's going on. The only thing I did was update to WP 4.2.2. Maybe there's an issue somewhere else with the plugin that didn't rear its ugly head until now.

**Comment by jrfnl** [comment]
Silly question maybe: Are all the required and recommended plugins installed and active ? If so, TGMPA is working as it should.

If they are not - could you please try again with the `develop` branch ? Your problem may well have already been solved there.

**Comment by bstump** [comment]
They are not already installed and active. I will check the develop branch. Thank you!

**Comment by jrfnl** [comment]
Ok, I look forward to hearing your findings when using the develop branch.

**Comment by jrfnl** [comment]
@bstump Just wondering if you've had a chance to test `develop` yet ?

**Comment by bstump** [comment]
We're good. It was a combo PEBKAC / WP error. I have a custom WordPress install setup with a custom theme. When I updated to WP 4.2.2 and did an install, WP wanted to use the default "twentyfifteen" theme. It showed that theme as the "active" theme, even though it didn't exist. As soon as I told it to make my custom theme active, it was good to go. Strange that WP would install and set a theme that doesn't even exist as the default one...

**Comment by jrfnl** [comment]
Thanks for getting back to us and glad to hear it is solved.

> Strange that WP would install and set a theme that doesn't even exist on disk as the default one...

Not so strange considering WP *needs* a theme to work, so it always ships with a default theme (or rather a few - I seem to remember 4.2 ships with three) and will use that as a fall-back for if - for whatever reason - the preferred theme gets deactivated.
If you remove those themes and your theme would accidentally get deactivated, you have nothing to fall back on and WP will break.

**Comment by bstump** [comment]
WP needs a default theme to work, and it had one - mine. For some reason, however, instead of looking at the themes directory and pulling my theme, it activated a theme that didn't exist.
