### ISSUE TITLE
Bundled plugins with uppercase letters in slug

### ISSUE THREAD

**Issue by steveboj** [TGMPA/TGM-Plugin-Activation#401]
v 2.5.0a
When a packaged plugin contains uppercase letters in the slug, it is causing both the install and update functions to fail, e.g. 'LayerSlider'. and 'Ultimate_VC_Addons'.

This is happening when you first install bundled plugins and when you try to update them.

No errors are shown in the browser or console.

**Comment by jrfnl** [comment]
@steveboj Thanks for reporting this. I believe I've fixed it now. If you like, please test the changes in PR #403.

**Comment by jrfnl** [comment]
Oh and FYI - using uppercase characters in the plugin slug/directory path is against the WP coding conventions which is why I didn't account for it previously.
