### ISSUE TITLE
fwiw: loading plugins data from plugins.json

### ISSUE THREAD

**Issue by soderlind** [TGMPA/TGM-Plugin-Activation#404]
I really like TGMPA, but instead of storing plugin data in php, I load it from a plugins.json file (key, value is the same as you would have in php):

```json
[
    {
        "name": "Advanced Custom Fields",
        "slug": "advanced-custom-fields",
        "required": true,
        "force_activation": true,
        "force_deactivation": true
    },
    {
        "name": "Simple Comment Editing",
        "slug": "simple-comment-editing",
        "required": true,
        "force_activation": true,
        "force_deactivation": true
    }
]
```

I load the plugins.json file using the following code:

```php
$current_theme = wp_get_theme();
$plugins_data_file = dirname( __FILE__ ) . '/plugins/plugins.json';

if (file_exists($plugins_data_file)) {

    $plugins_data = file_get_contents($plugins_data_file);
    $plugins = json_decode($plugins_data,true);

    if ($plugins === null && json_last_error() !== JSON_ERROR_NONE) {
        $errormsg = json_last_error_msg();
         return add_action( 'admin_notices', function() use ( $plugins_data_file, $errormsg,  $current_theme) {
            $msg[] = '<div class="error"><p>';
            $msg[] = sprintf('<strong>%s</strong>: ',$current_theme->Name);
            $msg[] = sprintf('Failed to parse json string in <strong>"%s"</strong>, error: <strong>"%s"</strong>', $plugins_data_file , $errormsg);
            $msg[] = '</p></div>';
            echo implode( PHP_EOL, $msg );
        });
     }
}
```

You'll find the full example at my site: http://soderlind.no/wordpress-theme-development-add-and-activate-required-plugins/

**Comment by jrfnl** [comment]
So what's your point ? What's the issue ?

(quite apart from the fact that you *should* be using the WP Filesystem for any file operations and doing that for a json config/settings file will get annoying *really* quickly unless you can use direct file operations)

**Comment by soderlind** [comment]
No issue :) Just a fwiw, but you have a good point, I've should (and will) use the WP Filesystem. Thank you for pointing that out to me.

**Comment by jrfnl** [comment]
@soderlind Please don't. Use the PHP array as per the example file instead.
The reason why it's better to use the settings array than a json file with the WP Filesystem is that - depending on the server configuration - the FS might need to ask for FTP/SSH credentials to be able to read a file. I can't imagine you'd want to burden people on those kind of servers with having to enter their credentials on *every* single admin page load. For me personally, that would easily be a reason to uninstall a theme, no matter how good the theme.

**Comment by soderlind** [comment]
ok, point taken and learned :)

**Comment by GaryJones** [comment]
I do kind of like the idea of storing plugin registration as JSON, and having the path of that file passed to TGMPA config, but it'd probably be a feature for the sake of being a feature. Not something we'd likely want in TGMPA core, but an interesting extension, especially if we ever made it as a WP Core feature plugin.

**Comment by soderlind** [comment]
Thank you

**Comment by jrfnl** [comment]
@GaryJones I've done something similar - against all my own objections - for a customer including an admin screen to create the json file. Not a good idea, but customer is king....

All the same, I'm just thinking - what *might* be more interesting would be a form as part of the TGMPA website which will create the PHP config/settings file for people. Including an option to upload an existing config file so someone could adjust an existing config.

For theme builders who aren't very familiar with PHP, this might save them some headaches.

**Comment by GaryJones** [comment]
+1 on that idea. Put the config as a new ticket. Perhaps we can have TGMPA look for ` tgmpa.json` file in the current or parent directory as the class file, save having to pass the path through - it'l just work.

**Comment by jrfnl** [comment]
Issue #405 created for this.
