### ISSUE TITLE
WordPress Multisite network admin plugins

### ISSUE THREAD

**Issue by CHEWX** [TGMPA/TGM-Plugin-Activation#406]
Hi,

Have looked around but cannot find the ability to Network add plugins with TGM. 

I know I can do this per Multisite, but would like to do this at a Network level for all within. I guess, you would have to do this manually, as you would only need to do it once !?

Just confirming.

Thanks.

**Comment by CHEWX** [comment]
Just realised, I can install on a multisite level and then go back to network admin and add to network.

**Comment by jrfnl** [comment]
@CHEWX TGMPA is currently not (fully) compatible with multi-site. This is on the roadmap for v3.0. #394
