### ISSUE TITLE
New update feature not working with some plugins

### ISSUE THREAD

**Issue by steveboj** [TGMPA/TGM-Plugin-Activation#407]
I am having problems using the new updating features in 2.5a with three plugins:

1. LayerSlider v5.3.2 to v5.4.0
Running the updater just returns the 'This plugin is at the latest version.' message.
This is caused by the plugin folder name containing uppercase letters (LayerSlider) when the plugin file name is all lowercase (layerslider.php).
If you change the file name in the active plugin directory to 'LayerSlider.php' the update process will then work successfully.

2. Visual Composer v4.4.2 to v4.5.1
The updater seems to ignore the 'source' you enter and tries to download the update from Envato.
It returns the messages 'Downloading package from invite invite market...' and 'To receive automatic updates license activation is required, etc.'

3. Easy Social Share Buttons for Wordpress v2.0.3 to v2.0.6.1
This also returns the message 'This plugin is at the latest version.' message.
I haven't been able to figure out why.

Let me know if you need any more details.

**Comment by GaryJones** [comment]
Regarding 1., [this commit](https://github.com/TGMPA/TGM-Plugin-Activation/pull/403) a couple of days ago should have fixed that, so please update to the latest development version.

**Comment by jrfnl** [comment]
Regarding 2: from the wording of the messages, it suspect that that VC is doing the overruling of the update source itself (using the normal WP hooks), but as their source code is not public, I can't verify if that's the case.

Regarding 3: please show us the settings array you are using for the plugin.

**Comment by steveboj** [comment]
@GaryJones The issue fixed in the most recent commit affected all plugins with uppercase letters (both on install and on update). This new one is only on update and only seems to affects plugins where the plugin folder name is formatted differently to the file inside, e.g. LayerSlider have have uppercase letters in their folder name, but not in the php file name.

**Comment by GaryJones** [comment]
Thanks for the clarification @steveboj - we'll look into that.

**Comment by steveboj** [comment]
@jrfnl I've just tested again on a fresh WP install with twentyfifteen and a basic TGM config and have run into the same problems with both Visual Composer and ESSB. Please see my code below along with a screenshot of the results screen.

Let me know if you would like me to send you copies of the relevant zip files and how I can send them to you.

```

require get_template_directory() . '/inc/class-tgm-plugin-activation.php';

add_action( 'tgmpa_register', 'my_theme_register_required_plugins' );

function my_theme_register_required_plugins() {
 
    $plugins = array(
 
        array(
            'name'               => 'WPBakery Visual Composer',
            'slug'               => 'js_composer',
            'source'             => get_stylesheet_directory() . '/inc/js_composer-4.5.1.zip',
            'required'           => true,
            'version'            => '4.5.1',
            'force_activation'   => false,
            'force_deactivation' => false,
        ),
        
        array(
        	'name'     				=> 'Easy Social Share Buttons for WordPress',
        	'slug'     				=> 'easy-social-share-buttons',
        	'source'   				=> get_template_directory() . '/inc/easy-social-share-buttons-2.0.6.1.zip',
        	'required' 				=> true,
        	'version' 				=> '2.0.6.1',
        	'force_activation' 		=> false,
        	'force_deactivation' 	=> false,
        ),
 
    );
 
    $config = array(
        'default_path' => '',                      // Default absolute path to pre-packaged plugins.
        'menu'         => 'tgmpa-install-plugins', // Menu slug.
        'has_notices'  => true,                    // Show admin notices or not.
        'dismissable'  => true,                    // If false, a user cannot dismiss the nag message.
        'dismiss_msg'  => '',                      // If 'dismissable' is false, this message will be output at top of nag.
        'is_automatic' => false,                   // Automatically activate plugins after installation or not.
        'message'      => '',                      // Message to output right before the plugins table.
    );
 
    tgmpa( $plugins, $config );
 
}

```

![screenshot 2015-05-14 11 05 40](https://cloud.githubusercontent.com/assets/9254088/7630023/d65b6e96-fa29-11e4-8406-50005241c4c7.png)

**Comment by jrfnl** [comment]
@steveboj Could you mail me 2 .zips for each of these plugins ? the previous one which you already had installed and the version to which you are trying to update ? Thanks. You can mail them to me @ adviesenzo dot nl

**Comment by steveboj** [comment]
@jrfnl Thanks, I have just emailed you the relevant zip files.

**Comment by jrfnl** [comment]
@steveboj Thanks for sending me the files. I've done some test runs with them, here are my findings:

**WP Bakery Visual Composer**:
As I suspected that error does not come from TGMPA, but from WPBVC. They overrule the WP download URL/upload we provide and as it's an commercial plugin I'm not inclined to provide a work-around in the TGMPA code.

**Easy Social Share Buttons**:
To my surprise, ESSB does something similar. They in turn overrule the setting of the update transient which is necessary for TGMPA/WP updater to work. They use the [Update Checker library](https://github.com/YahnisElsts/plugin-update-checker) to do so.
As this is non-standard plugin behaviour, I'm again not inclined to provide a work-around for this in TGMPA.

All the same, the simple way to get round this for both plugins is to deactivate the plugin, run the upgrade via TGMPA and then activate the plugin again, as while the plugin is deactivated, their hooks are deactivated as well.

**Comment by steveboj** [comment]
@jrfnl Thanks for the extra info - I will alert the plugin developers.

Did you have a chance to look into the issue that affects LayerSlider? I know what they've done is also non-standard, but I think it would make sense for TGMPA to be able to work with established plugins that are setup like that.

**Comment by jrfnl** [comment]
@steveboj As @GaryJones pointed out in his original comment - that has already been fixed a few days ago via PR #403.

Regarding the other plugins - the behaviour is obviously by design, so I'm not sure what you're hoping to achieve by contact the devs. For ESSB, they provide their own update checking and I get the impression that they are not showing the 2.0.6.1 update yet as released through that. If they did, it would work, though again not via bundled, but they will provide their own download URL.

**Comment by steveboj** [comment]
@jrfnl The LayerSlider issue is slightly different to the one fixed in the last commit. I clarified it here = https://github.com/TGMPA/TGM-Plugin-Activation/issues/407#issuecomment-101979681

**Comment by jrfnl** [comment]
@steveboj The filename itself shouldn't really affect how it works, but as this - again - is a non-public commercial plugin, could you please send me two copies (older, newer) of the files so I can test and see what's going on ?

**Comment by steveboj** [comment]
@jrfnl Thanks, I've just sent you the two files.

**Comment by jrfnl** [comment]
@steveboj Thanks, will have a look when I have the time.

**Comment by jrfnl** [comment]
@steveboj I've done some tests with LayerSlider and cannot re-produce the issue you reported.

Tests I ran:
* Single install 5.3.2, update `$plugins` to point to 5.4.0, run (single) update, activate => success.
* Single install 5.3.2, activate 5.3.2, update `$plugins` to point to 5.4.0, run (single) update => success.
	I did find one odd thing in this scenario and that is that after the update the TGMPA screen initially shows that the plugin is no longer active, but after re-loading the screen, the plugin (correctly) shows as active.
* Bulk-install 5.3.2, update `$plugins` to point to 5.4.0, run bulk-update, activate => success.
* Bulk-Install 5.3.2, activate 5.3.2, update `$plugins` to point to 5.4.0, run bulk-update => success.

I'm looking into the issue I mention in bullet two, but other than that I can't find any issues with updating the LayerSlider plugin.

What settings are you using for LayerSlider ? I'd like to make sure it's not a combination of settings (other than the ones I've set) which is causing this.

**Comment by steveboj** [comment]
@jrfnl I've just tested on a fresh install with twentyfifteen and LayerSlider is updating correctly, so maybe the problems I had before were caused by something else in the theme or the other plugins I was having troubles with. Sorry, I should have checked this on a fresh install before.

One issue I noticed similar to the one you mentioned in your second bullet point is when force_activation is set to true. You can still see the link to 'Deactivate' that plugin and when you click it says that plugin has been deactivated - but when you refresh the page the plugin still shows as active.
Perhaps when force_activation is set to true the 'Deactivate' link should just be hidden.

**Comment by jrfnl** [comment]
> You can still see the link to 'Deactivate' that plugin and when you click it says that plugin has been deactivated - but when you refresh the page the plugin still shows as active.
Perhaps when force_activation is set to true the 'Deactivate' link should just be hidden.

@steveboj I actually already implemented that a little while back - I think it was part of the update flow PR - https://github.com/TGMPA/TGM-Plugin-Activation/commit/439663cead0997d4d7a3fe3cee6f5bea813d09d7

**Comment by steveboj** [comment]
Re Visual Composer: I've just found they already provide a $disable_updater option you can use to prevent their updater conflicting with the new TGM. See https://wpbakery.atlassian.net/wiki/pages/viewpage.action?pageId=524297

**Comment by jrfnl** [comment]
@steveboj Thanks for that update. Are you ok with me closing this issue ?

**Comment by steveboj** [comment]
Yes, thanks Juliette.

**Comment by pavot** [comment]
Hi Juliette (@jrfnl),
I'm sorry for reopening this ticket.

Is there any way to make TGMPA to forcibly deactivate the plugins it's trying to update? This should fix the issues we have with custom solutions/classes like plugin-update-checker that break TGMPA work. 

I faced the same problems raised in this ticket but with other premium plugins that use plugin-update-checker and can't find any solution.

Tanks for your time.

**Comment by jrfnl** [comment]
Hi @pavot, we defer to WP core for the actual updating and WP core does not do so either except in a certain combination of circumstances.

AFAIR the only time this issue will rear its head is when you try to get TGMPA to update from a bundled plugin version rather than letting it update from the external source the plugin itself points to.

There's a reason for those plugins to have those update routines, so I'm still not inclined to overrule that.

If you use a customized version of the plugin and bundle that, I would suggest you change the plugin name and slug for your customized version and remove the build-in upgrade check as part of your customization.

If you don't customize it, then there is no reason to force update from a bundled version rather than update to the official version from an external source.

**Comment by pavot** [comment]
Thanks for your answer Juliette @jrfnl.
In our themes we include the premium plugins (extended license from author). We do release updates only after new version of the plugin fully tested with our theme to make sure it will not break anything on our client websites. Our theme buyers can't use native update from the premium plugins as they never bought it directly.

Anyway thanks for your time to explain me the situation.

**Comment by jrfnl** [comment]
Hi @pavot, I see where this is coming from now. I would suggest to talk with the premium plugin developers.
If they offer extended licenses which are not supposed to update through the normal (external) channel, they might be able to detect that extended license from within the plugin and add a conditional to only run their upgrade routine if the license is not of the extended variety.

Hope this helps. Sorry I can't be of more help at this moment.

**Comment by vburlak** [comment]
Hi everybody. I'm have the same problem when updating Visual Composer with extended license in my product.
@jrfnl , hope that the problem will be solved very simply

**Comment by vernondegoede** [comment]
HI @jrfnl ,

I'm experiencing the same issue as well. Our buyers didn't download Visual Composer directly from Codecanyon, we did it for them. 
In my $plugins[] array, I specified the 'source' to the updated Visual Composer .zip file. 
The plugin already seems to detect the plugin has been pre-packed. Why not just download it from that source instead of forcing them to fill in information they don't have? 

Cheers,
Vernon

**Comment by jrfnl** [comment]
@vburlak @vernondegoede 

1. This issue is closed. Commenting on it is not going to help.
2. Please read the whole thread. The solution to this was already provided by @steveboj in https://github.com/TGMPA/TGM-Plugin-Activation/issues/407#issuecomment-106793672

**Comment by vernondegoede** [comment]
Sorry @jrfnl, I missed that one. 
Thanks a lot!

**Comment by seventhqueen** [comment]
Check this out for Visual composer and make it work until you update to a version when they fixed it 
https://gist.github.com/seventhqueen/54d941cba1c31087bb1dd79959ab5948

**Comment by jrfnl** [comment]
@seventhqueen Unfortunately that is not the best way to go about it.
Again, please see https://github.com/TGMPA/TGM-Plugin-Activation/issues/407#issuecomment-106793672 for the proper solution.

-------------------------------

Short summary for people finding this thread in the future:
Add the below line of code to your `functions.php` to disable the external updater in Visual Composer:
```php
vc_set_as_theme();
```
