### ISSUE TITLE
String translation issue with WPML

### ISSUE THREAD

**Issue by femkhan** [TGMPA/TGM-Plugin-Activation#408]
Unwanted string translations are loading in the WPML strings kindly please update it or else is there anything there in the WPML which can escape this string from the file.

line #1115
esc_html_x( 'and', 'plugin A *and* plugin B', 'tgmpa' )

**Comment by GaryJones** [comment]
Why are these unwanted?

**Comment by femkhan** [comment]
Sorry I didn't find those strings in the output anywhere so thought it isn't necessary. Thanks for your response.

**Comment by GaryJones** [comment]
That string is likely part of the admin notice, but if you've only got one plugin registered, then it may not appear - doesn't mean it isn't potentially needed though.
