### ISSUE TITLE
Allow install plugins page to be moved. Or default to the plugins section.

### ISSUE THREAD

**Issue by brentjett** [TGMPA/TGM-Plugin-Activation#409]
This page shouldn't be listed under appearance, since it has nothing to do with the appearance of sites. It would be very helpful to allow the admin menu location to be configured or add a filter before add_theme_page() is called. If nothing else, this page should exist under plugins since it deals with installing plugins.

**Comment by jrfnl** [comment]
@brentjett This is already possible in the upcoming v2.5.0 version - test it out using the `develop` branch.

**Comment by brentjett** [comment]
Oh great, thanks so much for pointing it out!
