### ISSUE TITLE
Begin installing plugins - 404

### ISSUE THREAD

**Issue by pixel-industry** [TGMPA/TGM-Plugin-Activation#412]
I am testing v2.5 and I am getting 404 when click on "Begin Installing Plugins".
I changed "parent_slug" value to custom value: "pixely_options" (I want to move "Install plugins" under my custom Menu) and now URL for installing plugins is wrong:

http://localhost/wordpress-latest/wp-admin/pixely_options?page=install-required-plugins&plugin_status=install

In previous versions there was "parent_url_slug" parameter that now seems not to be available and instead of it "parent_slug" is used.

I am doing something wrong or this is bug?

Vladimir

**Comment by jrfnl** [comment]
@pixel-industry Yes, you are doing something wrong. The parent slug looks wrong.
Normally it would be something along the lines of `themes.php` or `options-general.php`. If you want to point to a custom menu, use the appropriate slug which I'm guessing will be `admin.php?page=pixely_options`

**Comment by pixel-industry** [comment]
Unfortunately it's not working with "admin.php?page=pixely_options". Submenu item won't show up.

Can someone please try to reproduce it as I think this is bug.

**Comment by jrfnl** [comment]
@pixel-industry I cannot reproduce it as I don't have access to pixely options. What is the page URL for your other sub-pages ?

**Comment by jrfnl** [comment]
@pixel-industry I've looked into this some more and just tried with another plugin which uses their own menu and it works like a dream. Use the slug like you originally did. But I'm guessing you've not set the appropriate capability. Try:
```php
'parent_slug'  => 'pixely_options'
'capability'   => 'manage_options',
```

**Comment by jrfnl** [comment]
Hand on, now I can also see the issue with installing - I'll have another look later to see if there is something I can do to fix that.

**Comment by jrfnl** [comment]
@pixel-industry I believe I've fixed it. You can test the fix in PR #417. Thanks for reporting and sorry for short initially. I shouldn't respond when I'm in a rush ;-)

**Comment by pixel-industry** [comment]
@jrfnl Thanks for looking into this. Everything is working fine now :)

**Comment by jrfnl** [comment]
@pixel-industry You're welcome & thanks for reporting the bug!
