### ISSUE TITLE
No permissions admin notice

### ISSUE THREAD

**Issue by GaryJones** [TGMPA/TGM-Plugin-Activation#414]
On logging in to another site where I'm not an administrator, I saw:

![screenshot 2015-05-18 22 18 30](https://cloud.githubusercontent.com/assets/88371/7690502/f39e4426-fdab-11e4-8fda-ea28fc7365a1.png)

While it's obviously good that a normal user can't install plugins, I don't think this message serves any purpose in being shown at all. As a user, I should not need to know what plugins a site should be running. Let's hide the message altogether and remove the associated strings that are currently being shown, and return early from any admin notice functions.

**Comment by jrfnl** [comment]
That completely depends on the kind of site. For a large multi-user site, I can see your point.
But for the more common - dev = admin, and three or four users which are just below admin, the message is useful. The dev might only be involved at the customers request and not keep up with which plugins need updating and such. Users need to know to contact the dev to get things working properly.

What about if we add a capability-check for which users can see it ? Something like author minimum ?

**Comment by GaryJones** [comment]
> Users need to know to contact the dev to get things working properly.

That's common sense already. 

I guess the problem is that the details of which plugins are shown, when the user can't do anything about _any_ plugins. How about author minimum, but also make the text generic like "This site requires one or more plugins that are not installed. Contact the ..."?

**Comment by jrfnl** [comment]
May be we should also consider to *only* show the notice if *required* plugins need to be installed or updated. And not show anything at all to non-admins if the notice would only deal with recommended plugins.

**Comment by jrfnl** [comment]
And now that updating is in - if the user has dismissed the message before, it would not show for new updates anymore. That kind of feels wrong as well.

Basically I think we may need to rename issue #353 to "Refactor/rethink complete notices logic" and collect all the different bits there.

And we need to think through whether that should something we still want to do for 2.5. It *is* already on the roadmap for 3.0

**Comment by MickeyKay** [comment]
I'm running into the same issue. My thought is that it would make sense to set the minimum user role or capability for which the notice should be displayed. That'd be a pretty simple fix.

**Comment by GaryJones** [comment]
Definitely not a 2.5.0 thing. Either add a capability check in 2.6.0, or rewrite completely for 3.0.0
