### ISSUE TITLE
2.5 testings

### ISSUE THREAD

**Issue by Zackio** [TGMPA/TGM-Plugin-Activation#416]
Testing out the the 2.5 release - After running an update from `appearance > install plugins` I get this when I go to the installed plugins page. I haven't made any changes to my settings though from 2.4. 

Just testing release to help out - eager for release - my customers are confused with updating plugins.

<pre>
( ! ) Notice: Undefined index: plugin in wp-admin/includes/update.php on line 281
Call Stack
#	Time	Memory	Function	Location
1	0.0033	402968	{main}( )	../plugins.php:0
2	1.5649	37998520	WP_List_Table->display( )	../plugins.php:481
3	1.5715	38002960	WP_List_Table->display_rows_or_placeholder( )	../class-wp-list-table.php:946
4	1.5715	38003056	WP_Plugins_List_Table->display_rows( )	../class-wp-list-table.php:1016
5	1.5875	38005040	WP_Plugins_List_Table->single_row( )	../class-wp-plugins-list-table.php:383
6	1.5936	38008912	do_action( )	../class-wp-plugins-list-table.php:646
7	1.5937	38010744	call_user_func_array:{/Users/admin/Sites/wp-skyline/wp-includes/plugin.php:496} ( )	../plugin.php:496
8	1.5937	38011168	wp_plugin_update_row( )	../plugin.php:496
</pre>

**Comment by jrfnl** [comment]
@Zackio Can you provide me with some more information please ? While the stack trace is good, I still have no clue now how to attempt to reproduce the issue.

[Guidelines for reporting bugs](https://github.com/TGMPA/TGM-Plugin-Activation/wiki/Guidelines-for-reporting-bugs)

**Comment by GaryJones** [comment]
Closing due to lack of feedback.
