### ISSUE TITLE
Call to undefined method TGM_Utils::validate_bool()

### ISSUE THREAD

**Issue by ghostpool** [TGMPA/TGM-Plugin-Activation#421]
TGMPA version 2.5.0-alpha
WordPress 4.2.2
PHP 5.3.28

A customer is receiving the following fatal error. I cannot replicate the issue myself. Any ideas why this is occurring?

    Fatal error: Call to undefined method TGM_Utils::validate_bool() in /../../class-tgm-plugin-activation.php on line 1261

These lines are the cause:

	$plugin['required']           = TGM_Utils::validate_bool( $plugin['required'] );
	$plugin['force_activation']   = TGM_Utils::validate_bool( $plugin['force_activation'] );
	$plugin['force_deactivation'] = TGM_Utils::validate_bool( $plugin['force_deactivation'] );

**Comment by jrfnl** [comment]
@ghostpool No, sorry, can't really think of any reason why this would occur.
Depending on whether other themes/plugins also use TGMPA a different version may be loaded than the one you are including, but then these methods wouldn't be called either.

The only thing I can think of is an upzipping error or something, meaning that the file would be corrupt. You could ask the customer to (manually/FTP) install your theme/plugin again to see if they still get the error. (oh and check that your file included file *does* contain the class - it should be at the bottom of the file).

Other than that, [a stack trace](https://gist.github.com/jrfnl/5925642) might give some more idea on what's happening.

P.S.: I shouldn't have to point out that a version is in _alpha_ for a reason and shouldn't (yet) be used in production.

**Comment by GaryJones** [comment]
Closing through lack of feedback.
