### ISSUE TITLE
TGMPA 2.5 release date

### ISSUE THREAD

**Issue by anikitas** [TGMPA/TGM-Plugin-Activation#423]
First of all great job guys, your plugin is extremely helpful for Themes.

Do you have a rough estimate when version 2.5 will be officially released?
Update embedded Plugins feature will improve a lot the user experience for users.

I think everybody is waiting to update to 2.5 due to this feature.

Thanks in advance!

**Comment by ThemeSama** [comment]
Yes i waiting :)

**Comment by jrfnl** [comment]
When it's ready ;-) (though you won't have to be patient much longer)

**Comment by vburlak** [comment]
@GaryJones @thomasgriffin changelog.md shows that 2.5.0 is currently released(2015-06-12). 
Awaiting confirmation & stable tagged version in repo for install it via Composer.
Thx for a good job!

**Comment by jrfnl** [comment]
@vburlak Sorry about that, we did do the merge with master, but decided to wait on a reply to an external inquiry we made, for the formal release. I expect the formal release to be done within the week now though.

**Comment by vburlak** [comment]
Not worries about that. It's good news.
Cheers!

**Comment by vburlak** [comment]
@jrfnl Not worries about that. It's good news.
Cheers!

**Comment by jrfnl** [comment]
@vburlak @anikitas @ThemeSama v2.5 has been released ;-)
https://github.com/TGMPA/TGM-Plugin-Activation/releases
