### ISSUE TITLE
Contact-Form-7 Installation

### ISSUE THREAD

**Issue by efectiva** [TGMPA/TGM-Plugin-Activation#424]
The remote plugin package does not contain a folder with the desired slug and renaming did not work. Please contact the plugin provider and ask them to package their plugin according to the WordPress guidelines.

**Comment by GaryJones** [comment]
We have no connection to authors of the plugins you want to bundle. If you feel there's an issue with the way that _they_ are packaging _their_ product, _you_ should contact _them_.

**Comment by efectiva** [comment]
Sorry, just wrong slug name in cofing file - case sensitive

**Comment by shyambhat** [comment]
Hi @wordica. I have a similar issue with another theme (GK Contact) and seems like I'm the only one on the internet who has the issue with this theme. Could you add details of where this config file resides, where you had to check for cases? Thanks!

**Comment by jrfnl** [comment]
@shyambhat The config file is part of the theme and you should ask the theme author.
Again: we have no connections to author of themes or plugins which use TGMPA. If they didn't implement it correctly, please ask them to fix it.
