### ISSUE TITLE
Add hooks and filters

### ISSUE THREAD

**Issue by sccr410** [TGMPA/TGM-Plugin-Activation#439]
I am trying to use TGM to manage paid add-on plugins for my free plugin. Users pay and get a single license key. When they enter their license key, TGM becomes available to them.

When a user activates, I want to run a license check. It would be much easier if there were hooks that ran for the single/bulk install/activate processes.

**Comment by jrfnl** [comment]
@sccr410 

> When they enter their license key, TGM becomes available to them.

Sorry, but that's not what TGMPA is for. TGMPA can be used by several themes and plugins simultaneously and one plugin blocking access to TGMPA for others is not a desirable situation.

> When a user activates, I want to run a license check.

TGMPA uses the core activation functions for activation, so you can use the WP core hooks to do this.

**Comment by sccr410** [comment]
Disable is not the best word, I simply do not setup or call the tgmpa() function until they have entered their Pro license key. I am not doing anything to "block" TGMPA to any other plugins or themes - not even sure that is possible.

I will try hooking into core plugin activations, thanks for that tip.

**Comment by jrfnl** [comment]
Hi Derek, let me know how you get on. Hope using the core hooks will solve it for you.
