### ISSUE TITLE
Bundled plugin Update problem - "latest version" - all testing from FAQ complete - still error

### ISSUE THREAD

**Issue by bghouse** [TGMPA/TGM-Plugin-Activation#452]
I've just gone through everything i can here in the issues, plus the FAQ page, and still have a problem with upgrading a plugin bundled with our theme.  Referring to this FAQ  "A plugin says it needs an update, but when I try to update, it says 'The plugin is at the latest version'."

I have deactivated and tried updating, same issue.  Disabled all other plugins, same issue.  Contacted the developer of the plugin and receiving instructions to remove all the auto-updating code from the plugin, tried again - same issue.

The plugin is WP Pro Ads System 
The theme is a custom theme we are developing

My setup is to include the plugin bundled in the theme, and here are my settings
```php
 array(
            'name'               => 'WP Pro Advertising System', // The plugin name.
            'slug'               => 'wp_pro_ad_system', // The plugin slug (typically the folder name).
            'source'             => get_template_directory() . '/lib/plugins/wp_pro_ad_system.zip', // The plugin source.
            'required'           => true, // If false, the plugin is only 'recommended' instead of required.
            'version'            => '4.6.1', // E.g. 1.0.0. If set, the active plugin must be this version or higher.
            'force_activation'   => false, // If true, plugin is activated upon theme activation and cannot be deactivated until theme switch.
            'force_deactivation' => false, // If true, plugin is deactivated upon theme switch, useful for theme-specific plugins.
            'external_url'       => '', // If set, overrides default API URL and points to an external URL.
            'is_callable'        => '', // If set, this callable will be be checked for availability to determine if a plugin is active.
        ),
```
I'm running TGMPA v2.5.2.   

I'm out of ideas on how to solve this, and our release deadline on this theme is rapidly approaching.  Looking forward to any assistance you can provide

**Comment by jrfnl** [comment]
@bghouse Hi Barbara, I'm willing to take a look, but need more info.

Word of warning re:
> Contacted the developer of the plugin and receiving instructions to remove all the auto-updating code from the plugin

If I find the plugin is interfering with the normal WP upgrade process (which TGMPA uses for the upgrades), you're wasting my time and as my time is precious, I will not be happy.

* What is the WP version you are using ? Have you tested on different versions ?
* Are you doing a single plugin update or bulk update ? Better yet, describe in detail all the steps you take so I can try to reproduce it.
* What is the old version of WPAS you are trying to upgrade from ?

I will also need access to both an old as well as a new version of WPAS to test with. Haven't got access to it as it's a commercial plugin. You can put the files in a dropbox for me or mail them to me AT adviesenzo DOT nl.

**Comment by jrfnl** [comment]
FYI: any similar issues we've previously seen were all - without exception - caused by the plugins breaking the upgrade. See: https://github.com/TGMPA/TGM-Plugin-Activation/issues/407

**Comment by bghouse** [comment]
Thank you Juliette for the fast response.  I was doing additional testing based on the other issue you linked, and did a fresh install and added to the Twenty Fifteen theme to see if it would work.

The good news is it updated :-)  The very, very, very bad news is that it means there is something in our theme causing the problem.

We use Easy Digital Downloads for distributing our theme updates.  Have you heard of any "gotchas" that might lead me in the correct direction to troubleshoot this further?

**Comment by jrfnl** [comment]
Could it be related to local testing ? See:  https://github.com/TGMPA/TGM-Plugin-Activation/issues/288

Oh and save some of that scotch for me ;-)

**Comment by bghouse** [comment]
Nope, that shouldnt be it because I'm not putting the plugins into EDD, it's only the theme that gets updated that way, but I was wondering if something in that code was causing it.  Of course, I removed the routine and still had the problem - so it's gonna be another one of these days it seems

**Comment by jrfnl** [comment]
Ok, keep me informed. I'm interested to hear what is causing this.

**Comment by bghouse** [comment]
I definitely will, thank you.  I just tested in another theme we released last year, and as soon as I turned off the EDD update routine it worked.  So now I just need to find the cause in EDD....

**Comment by bghouse** [comment]
Hi Juliette - I've almost got this sorted.  I have the updates working now, but have run into another issue that I'm hoping you have a workaround for.  The WP Pro Ads system still sends a normal WP plugin update available notification, even though I've disabled that routine.  And then when I perform the upgrade via TGMPA, it pulls from the author's API url instead of locally where I have the plugin bundled. 

Is there a way I can use the external_url to work around this maybe?  Going to run some tests..

Oh, and the conflict I was having was this lovely code snippet I had found for supressing the update messages of bundled plugins - so that's out going forward :-)

**Comment by jrfnl** [comment]
I suggest you look for filters in the WP Pro Ads system plugin hooked into `site_transient_update_plugins` or `transient_update_plugins`. I suspect that's where the overruling is done.

**Comment by bghouse** [comment]
Thanks again Juliette.  At this point, it looks like we're just going to leave that one plugin updating from the developers site.  It's working now through TGMPA, but insists on going to their site to update, so Bob's your uncle.  Really appreciate the help!

**Comment by jrfnl** [comment]
You're welcome. Can we close the issue ?

**Comment by bghouse** [comment]
Yes, I'll close now thank you again.
