### ISSUE TITLE
Can't install bundled plugins

### ISSUE THREAD

**Issue by rogercoathup** [TGMPA/TGM-Plugin-Activation#453]
We are getting the following error message when attempting to install bundled plugins:

*The remote plugin package consists of more than one file, but the files are not packaged in a folder. Please contact the plugin provider and ask them to package their plugin according to the WordPress guidelines.*

The plugin ZIP files appear to be correct, and will install without problem when used directly from Plugins ... Add New

We have the following settings in in the register array:

        array(
            'name'      => 'UBS Projects',
            'slug'      => 'ubs-projects',
            'source'	=> get_stylesheet_directory() . '/inc/plugins/ubs-projects.zip',
            'version'	=> '2.0',
            'required'  => false,
        ),

The plugin ZIP expands to a folder ubs-projects containing the various plugin files and subfolders.

Please advise.

**Comment by jrfnl** [comment]
Hi, this is a notice from WP Core, not from TGMPA. For whatever reason the file included as bundled does not seem to unpack properly.

**Comment by rogercoathup** [comment]
It fails if the plugins have been zipped using the compression utility direct from the OSX finder (although, they work without problem if used from the wp-admin... plugins ... add new).

I recompressed them using the shell command line, and they work correctly.

**Comment by jrfnl** [comment]
Thanks for letting us know. Weirdly interesting as TGMPA calls the core functions to do the unpacking, so strange that it does work when using 'add new'.

**Comment by Zackio** [comment]
For reference sake. If you zip the plugins contents and not the folder it's self  (easy to do if you use something automated ), You will get this message.

The upload zip via wordpress will install fine as rogercoathup pointed out but not with TGM.  

It can look like it was ziped with a folder as mac os will unzip to the the zip name regardless. So its easy to think the folder structure is ok.

**Comment by jacobraccuia** [comment]
I am also having this issue.

I am on Mac OSX and using Gulp to create a zip file of my plugin and placing it in my theme.  I get the mentioned error when attempting to install.  If I install this same zip file manually via standard WP methods, it works fine.

Unzipping the file reveals one folder, with the name of the theme, and inside are the contents (like it's supposed to be).

I was able to get TGM to work by unzipping the .zip, rezipping it using native OSX 'archive' and then uploading to my theme.  I don't want to do this however, as it defeats the purpose of gulp.

If TGM is supposed to work exactly like the native WP features, I would expect any plugin I can upload via the admin to also work this way! 

Please let me know what else I can provide to help.

**Comment by Zackio** [comment]
I got this to work by setting the root in the zips task.

**Comment by jacobraccuia** [comment]
@Zackio can you please share your Gulp for setting the root?

I tried this:

```

gulp.task('zip', () => {
    return gulp.src(['plugin/**'], { root:'plugin/'})
        .pipe(zip('plugin.zip'))
        .pipe(gulp.dest(''));
});

```

**Comment by jacobraccuia** [comment]
I figured it out, for anyone using Gulp who runs into this issue:

```
gulp.task('zip', () => {
        return gulp.src(['plugin_name/**'], { base:'.'})
        .pipe(zip('plugin_name.zip'))
        .pipe(gulp.dest(''));
});
```

this fixes it.

Note: I still believe this is an issue with TGMPA, because if it works with the manual upload, it should work with TGMPA.

**Comment by jrfnl** [comment]
@jacobraccuia Thanks for sharing that. I'm sure it will be useful to someone.
Other than that - as stated previously, TGMPA uses the WP core code to do the unpacking.

**Comment by fahidjavid** [comment]
I could fix with:

`
{ base:'../'}
`

I tried `{ base:'.'}` but it didn't work maybe only in my case.

**Comment by Gremza** [comment]
Found the solution. al files in zip are not in a main folder. anzip files in a folder and then zip the folder with all files inside. It works

**Comment by arafatjamil01** [comment]
Fixed in my case. Just compressed the plugin using winrar instead of windows default compression process. Worked like charm.

**Comment by denizhanokumus** [comment]
Hello, I downloaded the following theme from envato market. When I try to import a plugin called ThemeTon, the plugin gives the following error. How can I solve this problem?

Error: `The remote plugin package consists of more than one file, but the files are not packaged in a folder. Please contact the plugin provider and ask them to package their plugin according to the WordPress guidelines.`

Theme URL: https://elements.envato.com/dropbeat-creative-dance-studio-wordpress-theme-JS5WMQY

**Comment by hmbashar** [comment]
When I create a zip file using the Node command (`npm run bundle`), I encounter an installation issue with TGM. The error message states:

> "The remote plugin package consists of more than one file, but the files are not packaged in a folder. Please contact the plugin provider and ask them to package their plugin according to the WordPress guidelines."

However, when I download the zip file from GitHub and upload that version to the remote server, it installs correctly.

**Comment by fahidjavid** [comment]
> When I create a zip file using the Node command (`npm run bundle`), I encounter an installation issue with TGM. The error message states:
> 
> > "The remote plugin package consists of more than one file, but the files are not packaged in a folder. Please contact the plugin provider and ask them to package their plugin according to the WordPress guidelines."
> 
> However, when I download the zip file from GitHub and upload that version to the remote server, it installs correctly.

Unzip the plugin you built with node and re-zip using the Mac utility. Your problem will be solved.
