### ISSUE TITLE
get_class() called without object from outside a class in .../class-tgm-plugin-activation.php on line 2866

### ISSUE THREAD

**Issue by jtsternberg** [TGMPA/TGM-Plugin-Activation#455]
Have you run into this issue before? https://wordpress.org/support/topic/warnings-22?replies=1#post-7274236

Is there a reason that would take place?

**Comment by jrfnl** [comment]
Please upgrade to the latest version 2.5.2. This issue was fixed.

**Comment by jtsternberg** [comment]
Thank you.
