### ISSUE TITLE
TGM attempts to download pre-packed plugin from remote source

### ISSUE THREAD

**Issue by kievins** [TGMPA/TGM-Plugin-Activation#456]
I have seen this happen with a specific premium plugin - Visual Composer. TGM attempts to download update from Envato Market despite the fact that the updated files are pre packed with theme. Install works fine, so the file sources are set properly. I have attached screenshots.

![screen shot 2015-08-11 at 23 21 17](https://cloud.githubusercontent.com/assets/8179571/9211079/055405d6-4080-11e5-92da-0d27766d65bf.png)
![screen shot 2015-08-11 at 23 21 26](https://cloud.githubusercontent.com/assets/8179571/9211080/05594104-4080-11e5-8d1b-f09db232fa91.png)

**Comment by jrfnl** [comment]
Just checking: I presume you closed this because you found the answer in issue #407 ? I.e. this is VC overruling TGMPA.

**Comment by kievins** [comment]
Yes, this is VC overriding TGMPA incorrectly.
