### ISSUE TITLE
Plugin action links are not removed on WP 4.3

### ISSUE THREAD

**Issue by wesm87** [TGMPA/TGM-Plugin-Activation#458]
I just upgraded to 4.3 on my dev server and afterward I noticed that the action links (activate, deactivate, etc.) are not being removed any more. I know there are some filters that are supposed to run automatically to take care of this but it looks like something is preventing them from working properly. I'm currently relying on this functionality in a number of WordPress themes that I've developed to prevent clients from accidentally disabling an essential plugin. The following fixed the issue for me:

```
$required_plugins = [
	// required plugins
];
add_filter( 'plugin_action_links', 'custom_filter_plugin_links', 10, 4 );
function custom_filter_plugin_links( $actions = array(), $plugin_file = '', $plugin_data = array(), $context = '' ) {
	// Return if the current plugin doesn't have a slug
	$plugin_slug = isset( $plugin_data['slug'] ) ? $plugin_data['slug'] : '';
	if ( empty( $plugin_slug ) ) {
		return $actions;
	}
	
	// Loop through our required / recommended plugins and compare to the current plugin
	foreach ( $required_plugins as $config ) {
		$slug = isset( $config['slug'] ) ? $config['slug'] : '';
		$required = isset( $config['required'] ) ? $config['required'] : false;
		
		// Disable the deactivate link if the slugs match and the plugin is required
		if ( $slug == $plugin_slug && $required ) {
			unset( $actions['deactivate'] );
		}
	}
	
	return $actions;
}

```

**Comment by jrfnl** [comment]
Actually, TGMPA never did that, so not something which stopped working. The only action link we manipulate similar to what you suggest is for plugins which are 'force activated'.

All the same, I did a quick check and found that that hook in wasn't done in the right place, PR #459 should fix that.

Other than that, this is an enhancement request.

**Comment by wesm87** [comment]
Sorry for the confusion, I actually was referring to the "force_activation" method that you mentioned. I always set "force_activation" to true for required plugins so targeting either option would have the same effect for my configuration. Thanks for resolving this so quickly.

**Comment by jrfnl** [comment]
No problem. Ok to close this issue now ?

**Comment by wesm87** [comment]
Yes, the issue is resolved so go ahead and close it :+1:
