### ISSUE TITLE
Adding class, does not validate WP Theme Check

### ISSUE THREAD

**Issue by davidperezgar** [TGMPA/TGM-Plugin-Activation#462]
Hello, I want to upload a theme in wordpress.org and I'm using the Theme check before I upload. 

It shows this Issue:

REQUIRED: class-tgm-plugin-activation.php. Themes should use add_theme_page() for adding admin pages.
Line 609: $this->page_hook = call_user_func( 'add_submenu_page', $args['parent_slug'], $args['page_title'], $args['menu_

Only has to change the function name?

**Comment by jrfnl** [comment]
Closing as duplicate of #460 ;-)

**Comment by jrfnl** [comment]
FYI: The  [Custom TGMPA Generator](http://tgmpluginactivation.com/download/), which is now available on the website, fixes this.
