### ISSUE TITLE
Theme check REQUIRED 

### ISSUE THREAD

**Issue by devariya** [TGMPA/TGM-Plugin-Activation#463]
Tested with latest WordPress version .
REQUIRED: class-tgm-plugin-activation.php. Themes should use add_theme_page() for adding admin pages.

Line 645: $this->page_hook = call_user_func( 'add_submenu_page', $args['parent_slug'], $args['page_title'], $args['menu_

**Comment by jrfnl** [comment]
Closing as duplicate #460
