### ISSUE TITLE
Found a translation function that is missing a text-domain. Function _n_noop, with the arguments.

### ISSUE THREAD

**Issue by aamirs332** [TGMPA/TGM-Plugin-Activation#466]
I have an issue, when i check with theme check or debug toolbar plugin following warning are coming.

WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'This theme requires the following plugin: %1$s.','This theme requires the following plugins: %1$s.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'This theme recommends the following plugin: %1$s.','This theme recommends the following plugins: %1$s.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'The following required plugin is currently inactive: %1$s.','The following required plugins are currently inactive: %1$s.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'The following recommended plugin is currently inactive: %1$s.','The following recommended plugins are currently inactive: %1$s.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'The following plugin needs to be updated to its latest version to ensure maximum compatibility with this theme: %1$s.','The following plugins need to be updated to their latest version to ensure maximum compatibility with this theme: %1$s.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'Sorry, but you do not have the correct permissions to update the %s plugin. Contact the administrator of this site for help on getting the plugin updated.','Sorry, but you do not have the correct permissions to update the %s plugins. Contact the administrator of this site for help on getting the plugins updated.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'Sorry, but you do not have the correct permissions to install the %s plugin. Contact the administrator of this site for help on getting the plugin installed.','Sorry, but you do not have the correct permissions to install the %s plugins. Contact the administrator of this site for help on getting the plugins installed.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'Sorry, but you do not have the correct permissions to activate the %s plugin. Contact the administrator of this site for help on getting the plugin activated.','Sorry, but you do not have the correct permissions to activate the %s plugins. Contact the administrator of this site for help on getting the plugins activated.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'Begin installing plugin','Begin installing plugins'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'Begin activating plugin','Begin activating plugins'

how i can solve theme? Please help me.
Kind regards,
Aamir Shahazad
Skype: global-it-sol

**Comment by GaryJones** [comment]
What version of TGMPA are you using? I believe all of our noop strings currently have text domains.

https://github.com/TGMPA/TGM-Plugin-Activation/blob/develop/class-tgm-plugin-activation.php#L337-L396

https://github.com/TGMPA/TGM-Plugin-Activation/blob/develop/example.php#L126-L185

It may be that your set of strings is missing it, if you copied from an old version.

**Comment by Otto42** [comment]
Yeah, the few times I've been handed themes that have this issue, the problem was not in TGMPA, but in the theme itself. Look at your own _n_noop calls.

**Comment by aamirs332** [comment]
Hello, thanks your kind response, actually  I was using old version of tgmpa, thanks again for you help

**Comment by huykon** [comment]
I am using the newest version is 2.6.1 but it still shows the same error. Can anyone help me?

**Comment by jrfnl** [comment]
@huykon Just to verify I've run the underlying tool which provides these messages over TGMPA v2.6.1 with the current TGMPA ruleset - which is very strict - and I cannot reproduce the error.

As said before, check your own configuration file in case you are overruling TGMPA strings, as the error does not come from TGMPA itself.
Better yet: use the [Custom TGMPA Generator](http://tgmpluginactivation.com/download/) to get yourself a fresh copy of TGMPA to be sure you have the correct version.

**Comment by huykon** [comment]
@jrfnl  Thank you very much. I have fixed that problem :)

**Comment by jrfnl** [comment]
@huykon Glad to hear it.
