### ISSUE TITLE
Disable Plugin that are not needed anymore?

### ISSUE THREAD

**Issue by iamntz** [TGMPA/TGM-Plugin-Activation#467]
Hi. I'm using TGM on a project that has now has some unused plugins (but activated). 

There is any way of forcing disabling the unused plugins? Or should I ask the users to do so?

Thanks!

**Comment by jrfnl** [comment]
@iamntz Thanks for asking. TGMPA does not support disabling/deactivating plugins, so yes, you should probably ask the users or suggest it to them.
