### ISSUE TITLE
404 at http://tgmpluginactivation.com/faq/Guidelines-for-reporting-bugs

### ISSUE THREAD

**Issue by cliffordp** [TGMPA/TGM-Plugin-Activation#468]
http://tgmpluginactivation.com/faq/#update-fails-at-latest-version links to http://tgmpluginactivation.com/faq/Guidelines-for-reporting-bugs (which is a 404) instead of https://github.com/TGMPA/TGM-Plugin-Activation/wiki/Guidelines-for-reporting-bugs, although https://github.com/TGMPA/TGM-Plugin-Activation/blob/develop/README.md already links correctly.

**Comment by jrfnl** [comment]
@cliffordp Thanks for reporting this. Fixed now.
