### ISSUE TITLE
ThemeCheck shows this error

### ISSUE THREAD

**Issue by nomansbeauty** [TGMPA/TGM-Plugin-Activation#470]
Hi,

We are receiving this  error while we check out theme using ThemeCheck. We never seen this before and not sure what it means or how to solve it. Can anyone so kind to tell us about this & some details on solution please?
Screenshot: https://www.dropbox.com/s/dfbnxp4952zm8f8/0001.png?dl=0

Thanks alot

**Comment by jrfnl** [comment]
Closing as duplicate of #466 (not our bug).

**Comment by nomansbeauty** [comment]
Thanks alot for the solution. Have a great weekend :)
