### ISSUE TITLE
'tgmpa' text domain

### ISSUE THREAD

**Issue by weavertheme** [TGMPA/TGM-Plugin-Activation#474]
I've just learned while working with Otto, the Theme Check author, on another issue that they don't consider using multiple text-domains with a theme to be acceptable practice.

The recommendation (and it may become a requirement) is to, at the moment, manually replace all instances of 'tgmpa' text domain strings with the theme's own text domain slug. As before, only a string constant may be used in translation function calls to specify the text domain - and that may need to be the theme text domain slug.

This is not a great choice as 'tgmpa' is used for multiple purposes. 

But if this becomes a new Theme Check requirement, it would be good if it were easier to make the change with a simple search/replace on a string unique to the text domain value.

**Comment by GaryJones** [comment]
Search and replace `, 'tgmpa'`. That's unique to text domains.

**Comment by weavertheme** [comment]
A good thing to know now.

The very latest Theme Check will now flag as an INFO if the theme uses more than one text domain:

"INFO: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
The domains found are weaver-xtreme,  tgmpa".

So while not yet a WARNING, it is likely to lead to questions from other theme developers, and this discussion has the solution!

**Comment by GaryJones** [comment]
Addressing the text domain is on the list. See #218 .

**Comment by jrfnl** [comment]
FYI: The  [Custom TGMPA Generator](http://tgmpluginactivation.com/download/), which is now available on the website, fixes this.

**Comment by milutinjaric** [comment]
No it still has the issue of not changing text domain

**Comment by nandlal-tjm** [comment]
I have same issue

**Comment by jrfnl** [comment]
@DJMIMi @nandlal-tjm The [Custom TGMPA Generator](http://tgmpluginactivation.com/download/) _will_ change the text-domain for you providing you give it the correct information.
If this is not working for you, please open a new topic with a bug report describing what you entered in the generator form and how the received zip file is different from what you expected.

**Comment by milutinjaric** [comment]
New issue opened here https://github.com/TGMPA/TGM-Plugin-Activation/issues/624
