### ISSUE TITLE
add_theme_page() Theme Check error

### ISSUE THREAD

**Issue by galengidman** [TGMPA/TGM-Plugin-Activation#475]
When running Theme Check on a theme using version 2.5.2, I get the following error...

```
REQUIRED: tgm-plugin-activation/class-tgm-plugin-activation.php. Themes should use add_theme_page() for adding admin pages.

`Line 646: $this->page_hook = call_user_func( 'add_{$type}_page', $args['parent_slug'], $args['page_title'], $args['menu_t ...
```

Since the wordpress.org uploader checks the theme before allowing an upload, this makes it so that I cannot even upload my theme. Any fixes for this coming?

**Comment by Otto42** [comment]
This is a fork that passes theme-check and removes the undesirable ability to add arbitrary admin menus.

https://github.com/Otto42/TGM-Plugin-Activation

**Comment by kisonic** [comment]
I have this error too:
REQUIRED: plugins/tgm-plugin-activation/class-tgm-plugin-activation.php. Themes should use add_theme_page() for adding admin pages.
Line 624: ```$this->page_hook = call_user_func( 'add_submenu_page', $args['parent_slug'], $args['page_title'], $args['menu_t```

**Comment by jrfnl** [comment]
Closing as the [Custom TGMPA Generator](http://tgmpluginactivation.com/download/), which is now available on the website, fixes this.
