### ISSUE TITLE
TGMPA "plugin mode"

### ISSUE THREAD

**Issue by AlexAlexandru** [TGMPA/TGM-Plugin-Activation#480]
I use TGMPA in my plugin to require an wordpress repo plugin.The problem is that it's saying "This theme requires...".How about a "plugin mode"?(This plugin requires...)

**Comment by jrfnl** [comment]
The strings are configurable. In other words, you can change that text yourself. See the example.php file in your download, http://tgmpluginactivation.com/configuration/ or https://github.com/TGMPA/TGM-Plugin-Activation/blob/develop/example.php#L126
