### ISSUE TITLE
Password Reset Redirect

### ISSUE THREAD

**Issue by lucaskeiser** [TGMPA/TGM-Plugin-Activation#483]
I received this email from a subscriber:

"Since I had not visited the website in a while I had to reset my password. After the reset mailer was sent I was redirected to this page:

http://oswnetwork.com/wp-admin/?tgmpa-dismiss=dismiss_admin_notices

It doesn't seem to contain any seriously sensitive data but still appears like something internal to you (high level add block and forum activity numbers). Decided to let you know in case this is not intended."

I do not know the details apart from this other than what he has posted but I believe this is unexpected behavior.

**Comment by jrfnl** [comment]
Interesting, but we'll need a lot more information to even attempt to investigate this.

See [reporting bugs](https://github.com/TGMPA/TGM-Plugin-Activation/wiki/Guidelines-for-reporting-bugs).

**Comment by jrfnl** [comment]
Closing due to lack of additional information / no response in months.
