### ISSUE TITLE
How to know if my requirements were met?

### ISSUE THREAD

**Issue by pablo-pacheco** [TGMPA/TGM-Plugin-Activation#484]
After creating some requirements, how can i check if my required plugins were properly installed and are active before i can really start my theme or plugin. 

For example, Is there a getErrors() method or something similar? So i can know it there are any required plugins that were not installed or aren't active

**Comment by jrfnl** [comment]
I presume you know about the WP native [`is_plugin_active()`](https://codex.wordpress.org/Function_Reference/is_plugin_active) ? Alternatively (better), you can check whether certain defines, classes or functions of the target plugin(s) exist using PHP functions like `defined()`, `function_exists()` or `class_exists()`.

If you're not concerned with individual plugins, but want to know if all plugins which were provided to TGMPA are active, you could use `TGM_Plugin_Activation::get_instance()->is_tgmpa_complete()`.

However, do realize that that method was designed for use by TGMPA and checks if TGMPA has _"nothing left to do"_, so it will return `false` if there are updates available or if recommended plugins are inactive.

**Comment by pablo-pacheco** [comment]
Yes i am aware of this function, but do you agree with me that once i am creating requirements using tgmpa, wouldn't it be cool to check if these requirements were met using tgmpa too? I think it's so natural or it is just me?

Or else i would have to do like you said and use this **is_plugin_active** function plus creating the requirements. In other words i'd have to do almost the same thing twice.

But I think this **is_tgmpa_complete()** function fullfills my needs. Thank you!
