### ISSUE TITLE
TGMPA is vulnerable to CSRF Vulnerability

### ISSUE THREAD

**Issue by SymbianSyMoh** [TGMPA/TGM-Plugin-Activation#487]
`/* Removed by TGMPA team as irresponsible disclosure */`

**Comment by devbau** [comment]
Would be nice to have more detailed report, otherwise it sounds like your personal ad. Maybe you are correct, but please provide related detailed report too. 

Thx!

**Comment by jrfnl** [comment]
Responsible disclosure would be appreciated though.
