### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by devbau** [TGMPA/TGM-Plugin-Activation#490]
Have you considered to update TGM Plugin Activation into PHP 5.3 compatible namespacing?

For example:

TGM_Plugin_Activation = \TGM\PluginActivation ?

**Comment by jrfnl** [comment]
We'd love to, but won't until WP core ups it's minimum requirement. (Currently 5.2.4)

**Comment by devbau** [comment]
Hi, thank you!


If you check PHP supported versions page: http://php.net/supported-versions.php, it tells that PHP 5.3 is already out of support.

If you check https://wordpress.org/about/requirements/, i tells:

To run WordPress we recommend your host supports:
PHP version 5.6 or greater
MySQL version 5.5 or greater

Just an idea. Usage of namespaces leads to major version change too. So why not to start development of version 3.0, which is based on namespaces and for older version to have only security fixes for certain period?

**Comment by jrfnl** [comment]
Actually even PHP 5.4 is EOL (End of Life). I'm well aware.
But until WP ups it's *__minimum__* requirement (this is not the same as *recommended* version), we will not change this. Too many themes and plugins out there using TGMPA and it's not up to us to force them to up their minimum requirements too.

**Comment by Oxibug** [comment]
TGMPA with unique namespace to be included into plugins [TGMPA uses Namespace](https://github.com/Oxibug/tgmpa-ns)

And TGMPA with unique classes working with themes [TGMPA in Classes](https://github.com/Oxibug/tgmpa-unique-cls) 

Both working together simultaneously in the same site whereas both are prefixed and you will see notifications separately and each one can be dismissed separately.

It helped me a lot, Hope it help you.

**Comment by jrfnl** [comment]
@Oxibug As WP has updates it's minimum version to PHP 5.6, we could consider adding namespaces now to TGMPA, though will probably wait a little longer as plugins/themes often support more than just the latest and greatest of WP.

Also: your version violates the basic principle of TGMPA which is that there should only be _one_ admin screen collecting the info of all plugins/themes for the admin end-user.
