### ISSUE TITLE
default_path being ignored for bulk installations of 'bundled' plugins

### ISSUE THREAD

**Issue by posborn001002** [TGMPA/TGM-Plugin-Activation#494]
For a bundled plugin, the behavior between clicking 'install' under the plugin name, and doing a bulk install is different

For 'install' it uses default_path, but for bulk, it doesn't, so ends up looking for 'http://myplugin.zip, if you are relying on the default_path setting.

**Comment by jrfnl** [comment]
@posborn001002 Which version of TGMPA are you using ?
If not the latest (v2.5.2), please upgrade and try again. I'm pretty sure this was solved in v2.5.0.

**Comment by posborn001002** [comment]
You are absolutely right - thanks!
