### ISSUE TITLE
If plugins are Installed, it runs the installer again

### ISSUE THREAD

**Issue by ahmadawais** [TGMPA/TGM-Plugin-Activation#496]
Consider I have two plugins required which are already installed but not activated. Instead of `activating` them a user can seletect them all and select `install` and apply. Which leads to 
```
An error occurred while installing Contact Form 7: Destination folder already exists.
```

This must not be possible, it should skip the install and just activate them.

**Comment by jrfnl** [comment]
Thank you for reporting.
While I don't agree that the plugin in that case should activate, I do agree, that some check to skip an install if a plugin is already installed would be a good idea. Will look into this when I have a chance.

**Comment by ahmadawais** [comment]
@jrfnl Or the option of install should not be there. 
One more thing, can we redirect the Return to Dashboard link to a link of our choosing? E.g. to our plugin?

**Comment by jrfnl** [comment]
> Or the option of install should not be there. 

It is only included in the 'bulk' list, not underneath the plugin if the plugin is already installed.

> One more thing, can we redirect the Return to Dashboard link to a link of our choosing? E.g. to our plugin?

I understand your desire for this, however, TGMPA uses *one* page to display required and recommended plugins from both plugins as well as theme(s). So if all of these would overrule the dashboard link to there own page, we'd get a 'battle of priorities' which - to me - does not seem very useful.

**Comment by ahmadawais** [comment]
@jrfnl Here's why I want this. 
When user activates the plugin and gets redirected to welcome page, there are 5 steps for him to start using it. 0th step is go activate/install these plugins, now user does that and after that the link says Return to Dashboard. If I can return them to `Go! Do the next step!`. That'd be a much better UX.

**Comment by jrfnl** [comment]
I understand, but another theme or plugin which the user has installed might want to do the same which is what I meant with a 'battle of priorities'....

**Comment by ahmadawais** [comment]
@jrfnl Got your point. But TGMPA is a pretty small library, would it be wrong if I get to configure it just for my theme or plugin? If you allow such configurations, then we could have a config file to change things like these and use the library without any conflicts.

**Comment by jrfnl** [comment]
> But TGMPA is a pretty small library

Actually it is used by thousands of themes and plugins, so chances of conflicts are a lot higher than you might think.

**Comment by ahmadawais** [comment]
@jrfnl I know it is being used by a lot of themes and plugins, by pretty small I meant by number of files. I care a lot about user experience that is why I said that. 

Little knowledge that I have about the class Thomas wrote, can you tell me what could be a confilict if I change the name of the class `TGM_Plugin_Activation` ?

**Comment by jrfnl** [comment]
@ahmadawais Just renaming the main class will not work. Also, if you go through the whole file and adjust everything what would need adjusting to properly create an isolated fork, you would IMHO create a deteriorated user experience as now the user will end up with two notices at the top of admin pages and two different pages to install plugins if another plugin/theme also uses TGMPA.

**Comment by ahmadawais** [comment]
Got it!
