### ISSUE TITLE
How to properly get properties outside of class via __get() method?

### ISSUE THREAD

**Issue by vburlak** [TGMPA/TGM-Plugin-Activation#525]
I've config inside `tgmpa_register` action:
```php
$config = array(
    'parent_slug'            => 'my_theme_dashboard',
    'menu'                      => 'my_theme_install_plugins',
);
tgmpa( $plugins, $config );
```
All works excellent. 
Now, I can't figure out how to use `__get()` method outside of `TGM_Plugin_Activation ` class to get configured `parent_slug` and `menu` properties.
If we try to access class instance — it's returns defaults values such as `tgmpa-install-plugins` and `themes.php`.
Any suggestions are welcome!

**Comment by jrfnl** [comment]
@vburlak To advise you best, please let us know why you want access to these properties.
if it is to alter the call to add the page to the admin menu, you can use the `tgmpa_admin_menu_args` filter for instance.

**Comment by vburlak** [comment]
@jrfnl i'm working on improvements for dtbaker/envato-wp-theme-setup-wizard#5 (see see how it works in short [demonstration video](https://www.youtube.com/watch?v=vMey1BrKP_A))
It's using TGMPA for plugin activation and now it's have hard coded default `page_slug` and `menu`. 
And now we need change it with values configured in TGMPA.

**Comment by jrfnl** [comment]
@vburlak Try this:
```php
$instance = call_user_func( array( get_class( $GLOBALS['tgmpa'] ), 'get_instance' ) );
var_dump( $instance->menu );
```

**Comment by vburlak** [comment]
@jrfnl beautiful, thx!
