### ISSUE TITLE
The future of TGMPA

### ISSUE THREAD

**Issue by jrfnl** [TGMPA/TGM-Plugin-Activation#530]
Since last summer, we've been slowly preparing ourselves to create the next version of TGM Plugin Activation (or TGMPA for short). The main issue we'd like to solve is multisite compatibility and we'd also like to reduce issues of conflicts between different versions of TGMPA running within one WP install.

We published a [roadmap](http://tgmpluginactivation.com/roadmap/), talked with some people of the WP core team about the possibility of TGMPA becoming a feature plugin and [asked for opinions](https://github.com/TGMPA/TGM-Plugin-Activation/issues/447) about this.

_**Now it is time for you to stand up and be heard.**_

We'd like to hear your opinion about the changes we are proposing.

Please help us define the future of TGMPA by taking ten minutes of your time to **[fill out the survey](http://goo.gl/forms/Fq1gbY9vCW)**.

Your opinion is much appreciated!

Also: please spread the word about the survey to other developers. The more, the merrier.

------------------------------------
You are receiving this invite to participate in the survey because you have expressed an interest in TGM Plugin Activation at one time or another by either contributing to it, watching the GH repo, starring the GH repo or forking it.

As there is no other way to reach people through GH, I'm using the mention system to reach you as an exception. Please follow our [Twitter account](http://twitter.com/tgmpa) to receive regular updates.

Thank you.

@thomasgriffin, @GaryJones, @zackkatz, @shivapoudel, @jeffsebring, @hugosaner, @vburlak, @jtsternberg, @cfoellmann, @tivnet, @johnbillion, @ctalkington, @michaelbeil, @NateWr, @Ninos, @richardtape, @grappler, @Webcreations907, @KingYes, @asadkn, @elvishp2006, @hedii, @krishna19, @mpeshev, @lennil, @maarcin, @lonchbox, @ryantanglao, @johnnypea, @iqtq, @netconstructor, @Nyota, @BHEADRICK, @ronaldsgailis, @laoladen, @marcinant, @greatdex, @krivinarius, @AvalonPixedo, @dariodev, @jfeliweb, @golchha21, @danielmartins, @estoeckel, @burbridgeconsulting, @stuartduff, @IngussNeilands, @azwiki, @andreiluca, @saas786

**Comment by jrfnl** [comment]
Since last summer, we've been slowly preparing ourselves to create the next version of TGM Plugin Activation (or TGMPA for short). The main issue we'd like to solve is multisite compatibility and we'd also like to reduce issues of conflicts between different versions of TGMPA running within one WP install.

We published a [roadmap](http://tgmpluginactivation.com/roadmap/), talked with some people of the WP core team about the possibility of TGMPA becoming a feature plugin and [asked for opinions](https://github.com/TGMPA/TGM-Plugin-Activation/issues/447) about this.

_**Now it is time for you to stand up and be heard.**_

We'd like to hear your opinion about the changes we are proposing.

Please help us define the future of TGMPA by taking ten minutes of your time to **[fill out the survey](http://goo.gl/forms/Fq1gbY9vCW)**.

Your opinion is much appreciated!

Also: please spread the word about the survey to other developers. The more, the merrier.

------------------------------------
You are receiving this invite to participate in the survey because you have expressed an interest in TGM Plugin Activation at one time or another by either contributing to it, watching the GH repo, starring the GH repo or forking it.

As there is no other way to reach people through GH, I'm using the mention system to reach you as an exception. Please follow our [Twitter account](http://twitter.com/tgmpa) to receive regular updates.

Thank you.

@vijay2579, @pagelab, @cythux, @kimil, @tookiez, @tekjava, @boygraceful, @cmwwebfx, @indaam, @rtbfreitas, @yohio, @luisabarca, @gingibash, @kevinp1, @barayuda, @themeblvd, @SyntaxThemes, @creotip, @chrisblakley, @rizedr, @bastosmichael, @QWp6t, @vantares, @seggev319, @martijn-van-der-kooij, @iworks, @anuragrath, @miguelramosfdz, @kaixersoft, @bboehm86, @citidm, @blueprintmrk, @devariya, @jyllstuart, @tojibon, @maciekkus, @adrianholobut, @sahin70, @Moonomo, @chirox, @dingo-d, @earthboundlight, @hyyan, @corvannoorloos, @lkraav, @s-cotton, @ThemeSama, @drewhammond, @DennisBarker, @BILLzzz

**Comment by jrfnl** [comment]
Since last summer, we've been slowly preparing ourselves to create the next version of TGM Plugin Activation (or TGMPA for short). The main issue we'd like to solve is multisite compatibility and we'd also like to reduce issues of conflicts between different versions of TGMPA running within one WP install.

We published a [roadmap](http://tgmpluginactivation.com/roadmap/), talked with some people of the WP core team about the possibility of TGMPA becoming a feature plugin and [asked for opinions](https://github.com/TGMPA/TGM-Plugin-Activation/issues/447) about this.

_**Now it is time for you to stand up and be heard.**_

We'd like to hear your opinion about the changes we are proposing.

Please help us define the future of TGMPA by taking ten minutes of your time to **[fill out the survey](http://goo.gl/forms/Fq1gbY9vCW)**.

Your opinion is much appreciated!

Also: please spread the word about the survey to other developers. The more, the merrier.

------------------------------------
You are receiving this invite to participate in the survey because you have expressed an interest in TGM Plugin Activation at one time or another by either contributing to it, watching the GH repo, starring the GH repo or forking it.

As there is no other way to reach people through GH, I'm using the mention system to reach you as an exception. Please follow our [Twitter account](http://twitter.com/tgmpa) to receive regular updates.

Thank you.

@samediamba, @fredserva, @goliveirab, @AlexanderPoellmann, @stormwild, @vskochko, @fiftin, @AncaIO, @adam1920, @floq-design, @f2010525, @sanderdewijs, @bewho, @Ricardo-Diaz, @sandfieldjp, @seokafasi, @eataesse, @davidmcdougal, @iamlisaross, @alixcan, @tjahyoahmad, @macpil, @olivM, @bhubbard, @ScottPhillips, @svlasov, @josespinal, @benackles, @yetti, @dimiro1, @brajeshwar, @sxalexander, @rmccue, @sksmatt, @marfarma, @linuxjuggler, @shawnsandy, @pdewouters, @sumobi, @Tarendai, @LeGaS, @bolstad, @BjornW, @seedprod, @bicho44, @d8n, @pderksen, @thecancerus, @dbooom, @kraftbj

**Comment by jrfnl** [comment]
Since last summer, we've been slowly preparing ourselves to create the next version of TGM Plugin Activation (or TGMPA for short). The main issue we'd like to solve is multisite compatibility and we'd also like to reduce issues of conflicts between different versions of TGMPA running within one WP install.

We published a [roadmap](http://tgmpluginactivation.com/roadmap/), talked with some people of the WP core team about the possibility of TGMPA becoming a feature plugin and [asked for opinions](https://github.com/TGMPA/TGM-Plugin-Activation/issues/447) about this.

_**Now it is time for you to stand up and be heard.**_

We'd like to hear your opinion about the changes we are proposing.

Please help us define the future of TGMPA by taking ten minutes of your time to **[fill out the survey](http://goo.gl/forms/Fq1gbY9vCW)**.

Your opinion is much appreciated!

Also: please spread the word about the survey to other developers. The more, the merrier.

------------------------------------
You are receiving this invite to participate in the survey because you have expressed an interest in TGM Plugin Activation at one time or another by either contributing to it, watching the GH repo, starring the GH repo or forking it.

As there is no other way to reach people through GH, I'm using the mention system to reach you as an exception. Please follow our [Twitter account](http://twitter.com/tgmpa) to receive regular updates.

Thank you.

@mampranx, @mattrude, @allolex, @sdenike, @norcross, @lori, @syntaxsugar, @anointed, @ali-sattari, @bstrahija, @neojp, @Woorg, @brewern, @sabreuse, @WraithKenny, @doozy, @djrmom, @Vaultman, @jmslbam, @CameronGilroy, @mikeschinkel, @od3n, @garyblankenship, @raphaelcosta, @djordjes, @sethrubenstein, @jasondavis, @mattwiebe, @matiskay, @bryansayler, @andreeib, @seancojr, @boogah, @dermotmcguire, @Japh, @ethanpil, @jkudish, @ftownes, @Dreyer, @kezugo, @brandondove, @thadallender, @willmot, @nathanielks, @ckcoyle, @julien-c, @kevindees, @thefrosty, @neverything, @paintedbicycle

**Comment by jrfnl** [comment]
Since last summer, we've been slowly preparing ourselves to create the next version of TGM Plugin Activation (or TGMPA for short). The main issue we'd like to solve is multisite compatibility and we'd also like to reduce issues of conflicts between different versions of TGMPA running within one WP install.

We published a [roadmap](http://tgmpluginactivation.com/roadmap/), talked with some people of the WP core team about the possibility of TGMPA becoming a feature plugin and [asked for opinions](https://github.com/TGMPA/TGM-Plugin-Activation/issues/447) about this.

_**Now it is time for you to stand up and be heard.**_

We'd like to hear your opinion about the changes we are proposing.

Please help us define the future of TGMPA by taking ten minutes of your time to **[fill out the survey](http://goo.gl/forms/Fq1gbY9vCW)**.

Your opinion is much appreciated!

Also: please spread the word about the survey to other developers. The more, the merrier.

------------------------------------
You are receiving this invite to participate in the survey because you have expressed an interest in TGM Plugin Activation at one time or another by either contributing to it, watching the GH repo, starring the GH repo or forking it.

As there is no other way to reach people through GH, I'm using the mention system to reach you as an exception. Please follow our [Twitter account](http://twitter.com/tgmpa) to receive regular updates.

Thank you.

@wesohaire, @petervanderdoes, @kazandjiev, @Dsyko, @ninnypants, @defries, @webstylr, @mimiflynn, @dstrojny, @devinsays, @gfazioli, @Larceniii, @jasoncaffee, @innerbot, @samargulies, @manovotny, @screamwork, @billortell, @TristanRineer, @wpstudio, @jsylvanus, @aschweigert, @eightygrit, @victorpetryk, @fjarrett, @avioli, @logoscreative, @tobli, @weskoop, @dtbaker, @icecaster, @axwax, @tubiz, @williejackson, @joshualynch, @davidosomething, @elodahl, @slowmove, @gsanjeevkumar, @zanematthew, @cdog, @sevenspark, @daltonrooney, @gburtini, @ChrisMooney, @fxbenard, @28inch, @wpsmith, @nakunakifi, @zmni

**Comment by jrfnl** [comment]
Since last summer, we've been slowly preparing ourselves to create the next version of TGM Plugin Activation (or TGMPA for short). The main issue we'd like to solve is multisite compatibility and we'd also like to reduce issues of conflicts between different versions of TGMPA running within one WP install.

We published a [roadmap](http://tgmpluginactivation.com/roadmap/), talked with some people of the WP core team about the possibility of TGMPA becoming a feature plugin and [asked for opinions](https://github.com/TGMPA/TGM-Plugin-Activation/issues/447) about this.

_**Now it is time for you to stand up and be heard.**_

We'd like to hear your opinion about the changes we are proposing.

Please help us define the future of TGMPA by taking ten minutes of your time to **[fill out the survey](http://goo.gl/forms/Fq1gbY9vCW)**.

Your opinion is much appreciated!

Also: please spread the word about the survey to other developers. The more, the merrier.

------------------------------------
You are receiving this invite to participate in the survey because you have expressed an interest in TGM Plugin Activation at one time or another by either contributing to it, watching the GH repo, starring the GH repo or forking it.

As there is no other way to reach people through GH, I'm using the mention system to reach you as an exception. Please follow our [Twitter account](http://twitter.com/tgmpa) to receive regular updates.

Thank you.

@Marco-G, @anthonydurand, @erikford, @shazdeh, @zamoose, @jancbeck, @johnleblanc, @mattbrett, @joshharbaugh, @JPry, @ggwicz, @wpdevco, @nWidart, @rafegoldberg, @enile8, @helenhousandi, @jloft, @coreymckrill, @naomicbush, @georgestephanis, @kyletheisen, @daankortenbach, @ryanve, @joffff, @nciske, @OleVik, @arpitnj, @feelfree82, @plavet, @skymaiden, @adityavyas, @stompweb, @saulsolorzano, @hermiteu, @labsecrets, @dgj2ba, @smeric, @Mr2P, @tarex, @ebinnion, @stevenbradley, @DanielBakovic, @boylecreations, @spikeygoat, @FrankM1, @shazahm1, @hmfs, @Onedin, @chrisvanpatten, @mustardBees

**Comment by jrfnl** [comment]
Since last summer, we've been slowly preparing ourselves to create the next version of TGM Plugin Activation (or TGMPA for short). The main issue we'd like to solve is multisite compatibility and we'd also like to reduce issues of conflicts between different versions of TGMPA running within one WP install.

We published a [roadmap](http://tgmpluginactivation.com/roadmap/), talked with some people of the WP core team about the possibility of TGMPA becoming a feature plugin and [asked for opinions](https://github.com/TGMPA/TGM-Plugin-Activation/issues/447) about this.

_**Now it is time for you to stand up and be heard.**_

We'd like to hear your opinion about the changes we are proposing.

Please help us define the future of TGMPA by taking ten minutes of your time to **[fill out the survey](http://goo.gl/forms/Fq1gbY9vCW)**.

Your opinion is much appreciated!

Also: please spread the word about the survey to other developers. The more, the merrier.

------------------------------------
You are receiving this invite to participate in the survey because you have expressed an interest in TGM Plugin Activation at one time or another by either contributing to it, watching the GH repo, starring the GH repo or forking it.

As there is no other way to reach people through GH, I'm using the mention system to reach you as an exception. Please follow our [Twitter account](http://twitter.com/tgmpa) to receive regular updates.

Thank you.

@mindctrl, @HowardMei, @maverickGeek, @abkfenris, @teetteet, @siriokun, @pastorjacklamb, @jrav, @miziomon, @EvGreen, @j-gardner, @subharanjanm, @Pixelous, @sarova, @sonnypgs, @atsek, @oldquest, @vangog, @twittem, @ChrisButterworth, @JohnBunka, @AdamFrieberg, @rebelpixel, @gasoved, @hectopod, @bryceadams, @brasofilo, @egasimus, @brentini, @tyl3r, @silviu-bucsa, @montchr, @timkinnane, @chrisvogt, @Jeni4, @maddisondesigns, @aryaprakasa, @128, @sscovil, @digitalclutch, @desrosj, @justnorris, @apotropaic, @cyberwani, @raybes, @rafalosinski, @abbotto, @hasinhayder, @designerken, @jeroenherczeg

**Comment by hedii** [comment]
a little spammy, no? :)

**Comment by jrfnl** [comment]
Since last summer, we've been slowly preparing ourselves to create the next version of TGM Plugin Activation (or TGMPA for short). The main issue we'd like to solve is multisite compatibility and we'd also like to reduce issues of conflicts between different versions of TGMPA running within one WP install.

We published a [roadmap](http://tgmpluginactivation.com/roadmap/), talked with some people of the WP core team about the possibility of TGMPA becoming a feature plugin and [asked for opinions](https://github.com/TGMPA/TGM-Plugin-Activation/issues/447) about this.

_**Now it is time for you to stand up and be heard.**_

We'd like to hear your opinion about the changes we are proposing.

Please help us define the future of TGMPA by taking ten minutes of your time to **[fill out the survey](http://goo.gl/forms/Fq1gbY9vCW)**.

Your opinion is much appreciated!

Also: please spread the word about the survey to other developers. The more, the merrier.

------------------------------------
You are receiving this invite to participate in the survey because you have expressed an interest in TGM Plugin Activation at one time or another by either contributing to it, watching the GH repo, starring the GH repo or forking it.

As there is no other way to reach people through GH, I'm using the mention system to reach you as an exception. Please follow our [Twitter account](http://twitter.com/tgmpa) to receive regular updates.

Thank you.

@jjeaton, @bassscape, @elusiveunit, @orqun, @iqbalperkasa, @mindsharestudios, @jgclifton, @Savantos, @lokielse, @jambox, @brettmhoffman, @bradp, @buffler, @tnorthcutt, @zagriyen, @iamkevingreen, @Darrenmeehan, @ScottScanlon, @vuduzombie, @geekz, @jchck, @bonny, @joemcgill, @squiter, @sparqvault, @dsutoyo, @maqdes, @drrobotnik, @feryardiant, @amrita-tc, @alpipego, @KaptinLin, @mintbird, @Smartik89, @philipnewcomer, @jampasilva, @janruehling, @adiraomj, @Braunson, @DevinWalker, @abouolia, @joshmedeski, @Firestorm-Graphics, @mandava, @rickyrauch, @GeorgieKirschner, @stahoos, @sebas, @codearachnid, @Cifro

**Comment by jrfnl** [comment]
Since last summer, we've been slowly preparing ourselves to create the next version of TGM Plugin Activation (or TGMPA for short). The main issue we'd like to solve is multisite compatibility and we'd also like to reduce issues of conflicts between different versions of TGMPA running within one WP install.

We published a [roadmap](http://tgmpluginactivation.com/roadmap/), talked with some people of the WP core team about the possibility of TGMPA becoming a feature plugin and [asked for opinions](https://github.com/TGMPA/TGM-Plugin-Activation/issues/447) about this.

_**Now it is time for you to stand up and be heard.**_

We'd like to hear your opinion about the changes we are proposing.

Please help us define the future of TGMPA by taking ten minutes of your time to **[fill out the survey](http://goo.gl/forms/Fq1gbY9vCW)**.

Your opinion is much appreciated!

Also: please spread the word about the survey to other developers. The more, the merrier.

------------------------------------
You are receiving this invite to participate in the survey because you have expressed an interest in TGM Plugin Activation at one time or another by either contributing to it, watching the GH repo, starring the GH repo or forking it.

As there is no other way to reach people through GH, I'm using the mention system to reach you as an exception. Please follow our [Twitter account](http://twitter.com/tgmpa) to receive regular updates.

Thank you.

@tmm153, @vsalda, @boov, @ivandotv, @carlfj, @sacas, @roykho, @Scott-Sampson, @stephenharris, @ArnaudBan, @jensk, @pmgllc, @smronju, @mnishihan, @jarrodfreeman, @RafaelOlivra, @mdsahib, @faiqfardian, @teamcrisis, @rilwis, @maximski, @chriswallace, @praveenvvstgy, @BronsonQuick, @jconroy, @DavidWells, @hamiltonmascioli, @afragen, @TCattd, @MrMaz, @derfriedrich, @PawelPatyk, @BassemN, @corradomatt, @acepek, @CiTroNaK, @tnog, @scarstens, @DennisHalmstad, @matthewsimo, @dionysia, @nathanbriggs, @tirnovanuaurel, @cynthusia, @jamigibbs, @gopperman, @brandoncamenisch, @pixline, @arrowthemes, @sgumz

**Comment by jrfnl** [comment]
Since last summer, we've been slowly preparing ourselves to create the next version of TGM Plugin Activation (or TGMPA for short). The main issue we'd like to solve is multisite compatibility and we'd also like to reduce issues of conflicts between different versions of TGMPA running within one WP install.

We published a [roadmap](http://tgmpluginactivation.com/roadmap/), talked with some people of the WP core team about the possibility of TGMPA becoming a feature plugin and [asked for opinions](https://github.com/TGMPA/TGM-Plugin-Activation/issues/447) about this.

_**Now it is time for you to stand up and be heard.**_

We'd like to hear your opinion about the changes we are proposing.

Please help us define the future of TGMPA by taking ten minutes of your time to **[fill out the survey](http://goo.gl/forms/Fq1gbY9vCW)**.

Your opinion is much appreciated!

Also: please spread the word about the survey to other developers. The more, the merrier.

------------------------------------
You are receiving this invite to participate in the survey because you have expressed an interest in TGM Plugin Activation at one time or another by either contributing to it, watching the GH repo, starring the GH repo or forking it.

As there is no other way to reach people through GH, I'm using the mention system to reach you as an exception. Please follow our [Twitter account](http://twitter.com/tgmpa) to receive regular updates.

Thank you.

@jplew, @KorvinM, @meydjer, @saenko-av, @maxxscho, @iamdangavin, @cliffordp, @webkod3r, @maximebeaudoin, @yankodimitrov, @proframework, @jpaezsa, @kennybills, @xmarcos, @starkfree, @nickrouty, @zilth, @bfintal, @luizrw, @EugenioPetulla, @alexVauch, @Shelob9, @erayalakese, @micahtaylor, @shshaw, @flowtwo, @nathangath, @reardestani, @keha76, @vanjek, @seankmchenry, @mcaskill, @knownasilya, @aronwp, @haleeben, @ahmadazimi, @rizqyhi, @dwiash, @frytaz, @CodeWaggle, @kharissulistiyo, @gndev, @sanchitsoni, @EricSeiler, @lumberman, @JvdZ, @Twanneman, @rrikesh, @unisphere, @eugelogic

**Comment by jrfnl** [comment]
Since last summer, we've been slowly preparing ourselves to create the next version of TGM Plugin Activation (or TGMPA for short). The main issue we'd like to solve is multisite compatibility and we'd also like to reduce issues of conflicts between different versions of TGMPA running within one WP install.

We published a [roadmap](http://tgmpluginactivation.com/roadmap/), talked with some people of the WP core team about the possibility of TGMPA becoming a feature plugin and [asked for opinions](https://github.com/TGMPA/TGM-Plugin-Activation/issues/447) about this.

_**Now it is time for you to stand up and be heard.**_

We'd like to hear your opinion about the changes we are proposing.

Please help us define the future of TGMPA by taking ten minutes of your time to **[fill out the survey](http://goo.gl/forms/Fq1gbY9vCW)**.

Your opinion is much appreciated!

Also: please spread the word about the survey to other developers. The more, the merrier.

------------------------------------
You are receiving this invite to participate in the survey because you have expressed an interest in TGM Plugin Activation at one time or another by either contributing to it, watching the GH repo, starring the GH repo or forking it.

As there is no other way to reach people through GH, I'm using the mention system to reach you as an exception. Please follow our [Twitter account](http://twitter.com/tgmpa) to receive regular updates.

Thank you.

@listingslab, @Meroje, @whyisjake, @Felodriozola, @wonderyak, @honryou, @Den3er, @FrankyG, @allendoerfer, @rpowis, @tatygrassini, @dazzlesoftware, @jasperf, @hilja, @leoj3n, @themightymo, @PittsburghChris, @jmsmrgn, @Shakibmir, @justinticktock, @JonBellah, @attomsoft, @erwanlescop, @scottlyttle, @zoerooney, @getresults, @haikbvn, @claudiosmweb, @gaomd, @aazev, @ravinderk, @Tmeister, @jawittdesigns, @danielpataki, @AlxMedia, @mbijon, @grantpalin, @bruno-barros, @garrettjohnson, @jbach, @igorlbg, @SErr0r, @attackant, @jwondrusch, @dflippo, @VincentStephens, @matchdav, @wpscholar, @davidcroda, @senlin

**Comment by jrfnl** [comment]
Since last summer, we've been slowly preparing ourselves to create the next version of TGM Plugin Activation (or TGMPA for short). The main issue we'd like to solve is multisite compatibility and we'd also like to reduce issues of conflicts between different versions of TGMPA running within one WP install.

We published a [roadmap](http://tgmpluginactivation.com/roadmap/), talked with some people of the WP core team about the possibility of TGMPA becoming a feature plugin and [asked for opinions](https://github.com/TGMPA/TGM-Plugin-Activation/issues/447) about this.

_**Now it is time for you to stand up and be heard.**_

We'd like to hear your opinion about the changes we are proposing.

Please help us define the future of TGMPA by taking ten minutes of your time to **[fill out the survey](http://goo.gl/forms/Fq1gbY9vCW)**.

Your opinion is much appreciated!

Also: please spread the word about the survey to other developers. The more, the merrier.

------------------------------------
You are receiving this invite to participate in the survey because you have expressed an interest in TGM Plugin Activation at one time or another by either contributing to it, watching the GH repo, starring the GH repo or forking it.

As there is no other way to reach people through GH, I'm using the mention system to reach you as an exception. Please follow our [Twitter account](http://twitter.com/tgmpa) to receive regular updates.

Thank you.

@ValiNiculae, @alexsani, @timnashcouk, @jcsrb, @thewaterbear, @austinteer, @edpittol, @seb86, @diplix, @pfefferle, @wunderdojo, @1shiharat, @AldoFieuw, @mjmeintjes, @tonym2323, @dcooney, @richjenks, @franzose, @sonnyt, @EmranAhmed, @amishbhagwagar, @acktacky, @afurculita, @WayneBuckhanan, @KoenRijpstra, @Shahab2905, @christianwach, @uditvirwani, @ihorvorotnov, @MrVibe, @usamurai, @moyus, @BFTrick, @ellenmva, @danieleschle, @peterhadorn, @Hordern, @edwinestrada, @joshuadavidnelson, @kopepasah, @OneTenEleven, @iscacopi, @ValenPan, @cnyyk, @adampatterson, @Paul-Browne, @js9600, @mgiulio, @LeBaux, @m-e-h

**Comment by jrfnl** [comment]
Since last summer, we've been slowly preparing ourselves to create the next version of TGM Plugin Activation (or TGMPA for short). The main issue we'd like to solve is multisite compatibility and we'd also like to reduce issues of conflicts between different versions of TGMPA running within one WP install.

We published a [roadmap](http://tgmpluginactivation.com/roadmap/), talked with some people of the WP core team about the possibility of TGMPA becoming a feature plugin and [asked for opinions](https://github.com/TGMPA/TGM-Plugin-Activation/issues/447) about this.

_**Now it is time for you to stand up and be heard.**_

We'd like to hear your opinion about the changes we are proposing.

Please help us define the future of TGMPA by taking ten minutes of your time to **[fill out the survey](http://goo.gl/forms/Fq1gbY9vCW)**.

Your opinion is much appreciated!

Also: please spread the word about the survey to other developers. The more, the merrier.

------------------------------------
You are receiving this invite to participate in the survey because you have expressed an interest in TGM Plugin Activation at one time or another by either contributing to it, watching the GH repo, starring the GH repo or forking it.

As there is no other way to reach people through GH, I'm using the mention system to reach you as an exception. Please follow our [Twitter account](http://twitter.com/tgmpa) to receive regular updates.

Thank you.

@izmayoub, @johanthuresson, @enginne, @mattbanks, @BrianBourn, @EusebiuOprinoiu, @chuckreynolds, @davenaylor, @GregWallace, @CodeSymbol, @mkoepke, @moyarich, @bangaliana, @rawzone, @johnie, @epait, @qwertydude, @jasonsturges, @someguy9, @kekkorider, @szepeviktor, @tomharrigan, @heywin, @cconover, @txd159, @sarukuku, @henrytriplette, @pshevtsov, @z-avanes, @iulitaro, @codybuell, @timnolte, @klihelp, @niaquinto, @raisonon, @mostafamaklad, @klongdesigns, @pzi, @dnlmr, @simonwj, @MickeyKay, @thednp, @posykrat, @lohic, @robyparr, @nayenhowlader, @mattts, @engmahi, @ruhanirabin, @indieocean

**Comment by nWidart** [comment]
Please stop this spam.

**Comment by gfazioli** [comment]
for me too, what wrong?!

**Comment by eightygrit** [comment]
You do realize that once someone is tagged, they are automatically following this thread? So because you tagged me in the third post, I'm getting pushed the same message on every subsequent post. You're spamming the shit out of everyone multiple times. There are better ways to doing this.

**Comment by wpstudio** [comment]
wow... some serious spam.  Please UNTAG me

**Comment by logoscreative** [comment]
Click the ‘View it on GitHub’ link, go to the right sidebar towards the top and click ‘Unsubscribe’ under notifications.


On January 26, 2016 at 9:55:57 AM, Giovambattista Fazioli (notifications@github.com) wrote:

for me too, what wrong?!

**Comment by jrfnl** [comment]
Oh darn! My sincere apologies to all!!!!!!
That really wasn't meant to happen. I'll rethink how to reach the other people.
