### ISSUE TITLE
dismiss wp nonce

### ISSUE THREAD

**Issue by miraged** [TGMPA/TGM-Plugin-Activation#534]
in function dismis()
line
`check_admin_referer( 'tgmpa-dismis-'` - ends with single 's'
but link 
`wp_nonce_url( add_query_arg( 'tgmpa-dismiss', 'dismiss_admin_notices' ), 'tgmpa-dismiss-' . get_current_user_id() )`
has two 'ss'

this must be fixed

**Comment by jrfnl** [comment]
Good catch! PR #535 should take of this.
