### ISSUE TITLE
`update-nag` class

### ISSUE THREAD

**Issue by webmandesign** [TGMPA/TGM-Plugin-Activation#540]
Hi guys,

I love this script and can't wait for 3.0! :)

I would like to suggest removing the `update-nag` class as [it mispositions the admin notice](http://envato.d.pr/109VI/5ZtP7vSE) which I was notified during a theme review process.

Or is it just my setup where I'm getting this layout?

Thanks and regards,

Oliver

**Comment by GaryJones** [comment]
What version of WP is that?

**Comment by webmandesign** [comment]
The most recent, 4.4.2

**Comment by jrfnl** [comment]
This has been fixed already in development via PR #509. The fix will be included in the 2.6 version.

**Comment by webmandesign** [comment]
Thank you!
