### ISSUE TITLE
Before/After updating plugin action hooks

### ISSUE THREAD

**Issue by BassemN** [TGMPA/TGM-Plugin-Activation#542]
Hi,
Are there any action hooks that fire before and after updating a plugin?
Thanks

**Comment by jrfnl** [comment]
TGMPA uses the WP Core functions for doing the actual upgrade, so you can use the hooks available in core. Such as `upgrader_process_complete`,

See https://developer.wordpress.org/reference/classes/wp_upgrader/run/

**Comment by BassemN** [comment]
@jrfnl Thank you very much
