### ISSUE TITLE
Change has_notices from a child theme

### ISSUE THREAD

**Issue by reliable-mantra** [TGMPA/TGM-Plugin-Activation#544]
Hi,

I would like to change has_notices from a child-theme. 

This is the code I tried and it adds the plugin but it doesn't update has_notices:

```php
/*
	Require Ajax Load More Plugin 
*/
function herald_register_ajax_load_more() {

	$plugins = array(
	  array(
			'name' 		=> 'Ajax Load More - Infinite Scroll',
			'slug' 		=> 'ajax-load-more',
			'required' 	=> true
		)
	);

	$config = array( 
		'has_notices'	=> true
	);

	tgmpa( $plugins, $config );

}
add_action( 'tgmpa_register', 'herald_register_ajax_load_more', 10, 1 );
```

**Comment by jrfnl** [comment]
Just a quick test - can you try changing the prio ? There might be another plugin or theme in the install also using TGMPA which is overruling your config. Lowering the prio should fix that. If it doesn't, we'll have to look further.

```php
add_action( 'tgmpa_register', 'herald_register_ajax_load_more', 11, 1 );
```

**Comment by reliable-mantra** [comment]
That is the solution!

Thank You very much for Your quick response.

**Comment by jrfnl** [comment]
Glad it helped.
