### ISSUE TITLE
The texts always assumes its a themes where its used.

### ISSUE THREAD

**Issue by nextgenthemes** [TGMPA/TGM-Plugin-Activation#545]
>				'notice_can_install_required'     => _n_noop(
					'This theme requires the following plugin: %1$s.',
					'This theme requires the following plugins: %1$s.',
					'advanced-responsive-video-embedder'
				), // %1$s = plugin name(s).
				'notice_can_install_recommended'  => _n_noop(
					'This theme recommends the following plugin: %1$s.',
					'This theme recommends the following plugins: %1$s.',
					'advanced-responsive-video-embedder'
				), // %1$s = plugin name(s).

This strings speak to the users as if its a theme but this makes no sense in a plugin context.

I think the setting `'parent_slug'  => 'plugins.php',` could be used to assume its being used in a plugin context and use strings with "Plugin" instead of "Theme" instead then.

// I just noticed that "this theme" and "this plugin" displayed is not ideal, even if user probably knows what theme plugin he just activated its being displayed on the general plugins page right? So it could be anything and it may be better to to just replace the string anyway and put your plugin name in there.

So my new Idea: `Plugin or Theme Name` setting right besides `id` that gets automatically included into the translation strings.

**Comment by jrfnl** [comment]
Hiya, there are a couple of issues with what you are suggesting (and with TGMPA in this particular area for that matter).
First of all, for a quick solution: these strings can be overruled per plugin/theme from the config they pass - see [configuration](http://tgmpluginactivation.com/configuration/#h-configuration-options) for more information.
Secondly (the TGMPA issue), TGMPA can be used within one install by several plugins and a theme at the same time. Each will overrule the config from the previous one which can lead to confusing admin notices all round.

Concerning the 'sane' defaults suggestion, the new [Custom TGMPA Generator](http://tgmpluginactivation.com/download/) goes some way toward providing more sane defaults for different situations.

Hope this helps.

**Comment by nextgenthemes** [comment]
Not sure why it was not obvious to you but I knew about that the strings can be overridden because thats what I mentioned above.

Also I don't see how the Custom Generator addresses anything of this. In fact I used it. It aks for a Name but then I see only a ID in the config. Also as you said my idea would not work the way TGMPA is build right now it seems. So when I now replace the string with my plugin name all other uses of the class will he showing my Plugin name, so basically the initial issue stands.

**Comment by jrfnl** [comment]
Thanks for that feedback. Unfortunately this will not be solved in TGMPA v2 anymore and most of the configurability of this will be removed in TGMPA v3 to prevent this confusion.

**Comment by nextgenthemes** [comment]
Well there is a easy fix for you could do without a big rewrite, just replace the text with "plugin or theme". I did that later.

I also abandoned this class because it was causing nightmare issues when I used it in my 50.000 installs plugin on wp.org. People have horribly outdated versions of this class in their themes that do not have the `if_class_exists` and cause fatal errors on peoples sites. I also had a issue with a never but still outdated version with that check inside a non-default filename in some theme that caused a white screen of death at the admin because either my or their version was not working with one site of our code. Totally horror, never again if I can avoid it.
