### ISSUE TITLE
Allow disabling the "hide menu item" via $config

### ISSUE THREAD

**Issue by AlexandruDoda** [TGMPA/TGM-Plugin-Activation#550]
Hey,

I am using the class and I am showing the plugins table inside one the tabs of one of the sub-pages. For that reason, the sub-page contains more than just the table and I don't want it to hide when there are no more plugins to install.

Perhaps there could be an array key inside the $config that says  `'hide_on_finish' => false` / true which allows the user to control that feature. Considering the table shows "return to the dashboard" anyway, there wouldn't be any broken permission issues at all.

PS - The way I implemented this as a list inside the tab is by setting the menu item to that sub-page and putting this as a callback to an add_section:

```
$installer = TGM_Plugin_Activation::get_instance();
$installer->install_plugins_page();
```

Cheers!

**Comment by jrfnl** [comment]
I believe what you intend can be accomplished quite easily without the need for a new config key. Try this code in your callback:

```php
$installer = TGM_Plugin_Activation::get_instance();
if ( ! $installer->is_tgmpa_complete() ) {
	$installer->install_plugins_page();
}
```

**Comment by jrfnl** [comment]
@AlexandruDoda Could you confirm this solved your issue ? If not, please let us know how we can help.
