### ISSUE TITLE
Hide the table header and footer when everything is complete.

### ISSUE THREAD

**Issue by AlexandruDoda** [TGMPA/TGM-Plugin-Activation#551]
Apparently, when there is nothing else to install, the header and footer of the table are empty but still take space (are visible):

<img width="603" alt="screenshot 2016-03-31 00 04 26" src="https://cloud.githubusercontent.com/assets/8274669/14160435/4812ffd4-f6d4-11e5-8041-5edc271136e7.png">

<img width="851" alt="screen shot 2016-03-31 at 00 05 52" src="https://cloud.githubusercontent.com/assets/8274669/14160459/667f6ba6-f6d4-11e5-8aa4-bacd6f6cf94c.png">

<img width="502" alt="screen shot 2016-03-31 at 00 06 04" src="https://cloud.githubusercontent.com/assets/8274669/14160461/6784e102-f6d4-11e5-96a1-27215b10b422.png">

I think these should disappear when there are no plugins to install as there is nothing inside them and only break the page aesthetically.

**Comment by jrfnl** [comment]
This is unrelated to TGMPA - these styles comes from WP core and as TGMPA does not register a page when there is nothing  to show, this is not something which IMHO should be solved in TGMPA.
