### ISSUE TITLE
Option to hide version via $config

### ISSUE THREAD

**Issue by AlexandruDoda** [TGMPA/TGM-Plugin-Activation#552]
Is there or can there be any option to hide the version below the plugins table? I am trying to build a minimalistic UI and was wondering if that's possible without using CSS.

<img width="362" alt="screen shot 2016-03-31 at 00 08 35" src="https://cloud.githubusercontent.com/assets/8274669/14160532/bb45b640-f6d4-11e5-9ebe-5e262028dff4.png">

**Comment by jrfnl** [comment]
This can be done with css. There is currently no other way.

We've seen numerous problems in the past with conflicts with several TGMPA versions being used within the same WP install. This number was added in response to that.
