### ISSUE TITLE
TGMPA translation / plugin strings conflict

### ISSUE THREAD

**Issue by spwebguy** [TGMPA/TGM-Plugin-Activation#554]
Hi there,

I have several plugins on the **WordPress plugin directory** and would like to use the WordPress translation system for my plugin translation. I checked my plugin translation page on WordPress.org and it's importing all the translatable strings from my plugin folder which includes **your** plugin strings. 

I would like to remove your strings from my plugin (text-domain) so that WordPress.org only takes my own strings for translation. Do you have any idea how I should do this? Is it clear enough (if not just let me know)? I thought of manually removing the translatable strings from your class, but I doubt that's the best way...

Thank you in advance for this.

**Comment by jrfnl** [comment]
@spwebguy Unfortunately the WP translation system does not (yet) look at the text domain when importing the strings, so no, there is currently no easy way to do this.

The upside, however, is that the WP translation system should recognize those strings in their system and as most of them are translated already (mostly for themes), there should be translations available already for quite a few languages. Meaning your translators won't need to spend much time on them.

**Comment by spwebguy** [comment]
Cool, thank you for this answer, it's really helpful.

I'll leave it this way then. Seems the right thing to do.
