### ISSUE TITLE
Update "Tested up to" in readme file

### ISSUE THREAD

**Issue by thomasgriffin** [TGMPA/TGM-Plugin-Activation#556]
The latest "Tested up to" says 4.2.0. With 4.5 coming out soon, we should go ahead and bump this to 4.5 (assuming everything functions as expected).

**Comment by jrfnl** [comment]
Hi Thomas, I expect v 2.6.0 should be ready for release round the same time. In that case, this is already covered in PR #461 which will be updated still for the actual release.
