### ISSUE TITLE
Theme Check requirement failure with TGMPA 2.5.2

### ISSUE THREAD

**Issue by batsteek** [TGMPA/TGM-Plugin-Activation#560]
When I check my theme + TGMPA 2.5.2 (basic setup) with the Theme Check plugin https://fr.wordpress.org/plugins/theme-check/ , I get the following message: 

REQUIRED: class-tgm-plugin-activation.php. Themes should use add_theme_page() for adding admin pages.
Line 641: $this->page_hook = call_user_func( 'add_submenu_page', $args['parent_slug'], $args['page_title'], $args['menu_t

WP: WP 4.5

**Comment by batsteek** [comment]
Ok, I answer to myself: solution is to define the distribution method in the generator. (in my case, wordpress.org)

**Comment by jrfnl** [comment]
And that's the correct answer too ;-)

For anyone who comes across this question at a later date: [download TGMPA via the Custom Generator](http://tgmpluginactivation.com/download/) & select the options which apply to your project, and in case of a theme which will be hosted on wordpress.org, the download you received will pass Theme Check.
