### ISSUE TITLE
php error messages "Invalid argument supplied for foreach()"  and "Undefined variable"

### ISSUE THREAD

**Issue by Smartit1** [TGMPA/TGM-Plugin-Activation#568]
Hi,
I am developing locally a wordpress theme and I am using the latest version of TGM-Plugin-Activation 2.5.2 , I inserted this code into functions.php 
```php
require_once( get_template_directory() . '/inc/class-tgm-plugin-activation.php' );
add_action( 'tgmpa_register', 'carthage_register_required_plugins' );
function carthage_register_required_plugins() {

	 //$config='abc';$plugins='abc';
	$plugins = array(

		array(
			'name'               => 'TGM Example Plugin', // The plugin name.
			'slug'               => 'tgm-example-plugin', // The plugin slug (typically the folder name).
			'source'             => get_template_directory() . '/plugins/tgm-example-plugin.zip', // The plugin source.
			'required'           => true, // If false, the plugin is only 'recommended' instead of required.
			'version'            => '2.5', // E.g. 1.0.0. If set, the active plugin must be this version or higher. If the plugin version is higher than the plugin version installed, the user will be notified to update the plugin.
			'force_activation'   => false, // If true, plugin is activated upon theme activation and cannot be deactivated until theme switch.
			'force_deactivation' => false, // If true, plugin is deactivated upon theme switch, useful for theme-specific plugins.
			'external_url'       => '', // If set, overrides default API URL and points to an external URL.
			'is_callable'        => '', // If set, this callable will be be checked for availability to determine if a plugin is active.
		),

$config = array(
		'id'           => 'carthage',            // Unique ID for hashing notices for multiple instances of TGMPA.
		'default_path' => '',                      // Default absolute path to bundled plugins.
		'menu'         => 'tgmpa-install-plugins', // Menu slug.
		'has_notices'  => true,                    // Show admin notices or not.
		'dismissable'  => true,                    // If false, a user cannot dismiss the nag message.
		'dismiss_msg'  => '',                      // If 'dismissable' is false, this message will be output at top of nag.
		'is_automatic' => false,                   // Automatically activate plugins after installation or not.
		'message'      => '',         ),
	);}

	tgmpa( $plugins, $config );
```
When I go to the site, it displays normally but I get these PHP errors:
* `( ! ) Notice: Undefined variable: plugins in ...\wp-content\themes\carthage\functions.php on line 53`
* `( ! ) Notice: Undefined variable: config in ...\wp-content\themes\carthage\functions.php on line 53`
* `( ! ) Warning: Invalid argument supplied for foreach() in ...\wp-content\themes\carthage\inc\class-tgm-plugin-activation.php on line 1922`

...in the WP dashboard. It displays too with these errors but no plugin appears in.
I verified every single parameter many times, tried with different plugins, always the same result (here I am trying with the example plugin).

Can you please help me to fix this? Thanks in advance.

**Comment by GaryJones** [comment]
[Line 1922 of 2.5.2](https://github.com/TGMPA/TGM-Plugin-Activation/blob/2.5.2/class-tgm-plugin-activation.php#L1922) is a comment, not a `foreach`, so please double check you've got the latest version.
(Admittedly, I'm not sure if the custom generator output changes so line numbers around - @jrfnl?)

As for your errors - you're defining the `$plugins` and `$config` variables inside a function, but then you close that function (`}`) on the line right before the `tgmpa(...)` is called. You probably want to move that `}` to after `tgmpa(...)` call, or delete it if one is already there.

**Comment by Smartit1** [comment]
Thanks xD I lost hours trying to figure out what's the problem, and it was just a misplaced bracket, just a little question: can I put this code in a separate php file or it must be in functions.php ?

**Comment by jrfnl** [comment]
@Smartit1 You can put the code anywhere you like, as long as you make sure you include the file before WP reaches the `init` hook at priority 10.

@GaryJones Yes, depending on the version generated some line numbers will change. All the same, in this case, the issue really was the bracket ;-)
