### ISSUE TITLE
2.6.0 and custom TGMPA Generator?

### ISSUE THREAD

**Issue by batsteek** [TGMPA/TGM-Plugin-Activation#583]
Hello TGMPA Team,

Do you plan to make 2.6.0 available through the generator in the coming days/weeks?

Thanks for all your great work!

**Comment by jrfnl** [comment]
*grin* A little patience goes a long way.... testing with the 2.6.0 zip now. Expect the website to be updated somewhere within the next 48 hours.

**Comment by batsteek** [comment]
No worries, I'm definitely not in a hurry, I was just curious!
Thanks for your answer Juliette :)

**Comment by jrfnl** [comment]
FYI: Custom Generator is updated ;-)
