### ISSUE TITLE
wp_list_table class should be included with project

### ISSUE THREAD

**Issue by UVLabs** [TGMPA/TGM-Plugin-Activation#586]
Highlighted in red on class reference page: https://codex.wordpress.org/Class_Reference/WP_List_Table

"This class's access is marked as private. That means it is not intended for use by plugin and theme developers as it is subject to change without warning in any future WordPress release. If you would still like to make use of the class, you should make a copy to use and distribute with your own project, or else use it at your own risk."

Maybe including it with the project is best.

**Comment by jrfnl** [comment]
It also says:
> To date, no major changes have occurred in this class or are scheduled to occur, so testing your plugin with beta/RC phases of WordPress development should be more than enough to avoid any major issues.

Which we do (test against development releases of WP) :sunglasses:

**Comment by UVLabs** [comment]
Great! Just looking out :)

**Comment by jrfnl** [comment]
Much appreciated!
