### ISSUE TITLE
Issue in plugin listing page after 2.6.0

### ISSUE THREAD

**Issue by ernilambar** [TGMPA/TGM-Plugin-Activation#587]
When I update TGM to 2.6.0 I got following in the plugin install page.
In this line, https://github.com/TGMPA/TGM-Plugin-Activation/blob/develop/class-tgm-plugin-activation.php#L2726 when `%1$s` is changed to `%s`, issue is resolved.

Screenshot - http://prnt.sc/b50e6w

**Comment by jrfnl** [comment]
Hi @ernilambar Thanks for reporting this. Would you mind testing out PR #588 to see if I fixed it correctly ?

**Comment by ernilambar** [comment]
@jrfnl Yes, I tried that PR and it worked as expected.

**Comment by jrfnl** [comment]
Great! Thanks for testing.

**Comment by jrfnl** [comment]
FYI: we just released v 2.6.1 which contains the fix for this issue. Website & Custom Generator will be updated within the next few hours.
