### ISSUE TITLE
%s doesn't work as it is supposed to

### ISSUE THREAD

**Issue by abaicus** [TGMPA/TGM-Plugin-Activation#589]
Hey guys! There seems to be an issue with the way this part of the table is echoed out.
![Uploading image.png…]()

`$actions['install'] = __( 'Install %s', 'theme-slug');`

**Comment by evgeniyshay** [comment]
`// Display the 'Install' action link if the plugin is not yet available.
			if ( ! $this->tgmpa->is_plugin_installed( $item['slug'] ) ) {
				/* translators: %s: plugin name in screen reader markup */
				$actions['install'] = __( 'Install %2$s', 'theme-slug' );
			} else {
				// Display the 'Update' action link if an update is available and WP complies with plugin minimum.
				if ( false !== $this->tgmpa->does_plugin_have_update( $item['slug'] ) && $this->tgmpa->can_plugin_update( $item['slug'] ) ) {
					/* translators: %s: plugin name in screen reader markup */
					$actions['update'] = __( 'Update %2$s', 'theme-slug' );
				}

				// Display the 'Activate' action link, but only if the plugin meets the minimum version.
				if ( $this->tgmpa->can_plugin_activate( $item['slug'] ) ) {
					/* translators: %s: plugin name in screen reader markup */
					$actions['activate'] = __( 'Activate %2$s', 'theme-slug' );
				}
			}`

**Comment by GaryJones** [comment]
Please try the version in `develop` branch, as it contains [this](https://github.com/TGMPA/TGM-Plugin-Activation/blob/develop/class-tgm-plugin-activation.php) fix.

**Comment by abaicus** [comment]
Thanks, @GaryJones ! :+1:

**Comment by jrfnl** [comment]
FYI: we just released v 2.6.1 which contains the fix for this issue. Website & Custom Generator will be updated within the next few hours.

**Comment by abaicus** [comment]
Thanks guys! Really appreciate it! :D
