### ISSUE TITLE
ThemeForest version

### ISSUE THREAD

**Issue by evgeniyshay** [TGMPA/TGM-Plugin-Activation#590]
ThemeForest requirements now include esc_html__(), esc_attr__() instead of __() & esc_html_e(), esc_attr_e() instead of _e().

**Comment by GaryJones** [comment]
@evgeniyshay Could you please link to the TF requirements documentation?

**Comment by evgeniyshay** [comment]
This is part of out theme review message on ThemeForest
4. Data Validation issues have been found in your theme. All dynamic data
must be correctly escaped for the context where it is rendered. -
http://codex.wordpress.org/Data_Validation -
http://developer.wordpress.com/themes/escaping/ -
https://vip.wordpress.com/2014/06/20/the-importance-of-escaping-all-the-things/
We are taking extra precautions with security issues now. Please perform a
global search for "echo quot; and escape ALL outputs. This will help ensure
there are no security issues.
6. Validate, sanitize and escape all data:
https://codex.wordpress.org/Validating_Sanitizing_and_Escaping_User_Data
also go over https://make.wordpress.org/themes/tags/writing-secure-themes/
And by the way ThemeForest forbit more than one text domain in the theme,
that's why theme text domain must use in plugin activator class too, like
in your wordpress.org package.

2016-05-18 18:23 GMT+03:00 Gary Jones <notifications@github.com>:

**Comment by jrfnl** [comment]
@evgeniyshay Regarding the escaping: TGMPA escapes *all* strings, but - as one should - strings are escaped late, i.e. at the point where they are echo-ed out as only then you know the context in which the string is used.
In some cases, this means that escaping and translation is not done in the same call. Escaping all strings at the point of translation does not make sense and will lead to double escaped strings.

@Stephen-Cronin Could you enlighten us about the above ?

> And by the way ThemeForest forbit more than one text domain in the theme, that's why theme text domain must use in plugin activator class too, like in your wordpress.org package.

Looking at the message, I get the impression that the `tgmpa` text-domain is no longer allowed in contrast to what was discussed earlier in #519.
Is that true ? In that case, there is no difference in requirements anymore between wp.org and Themeforest and we could merge these two select options into one for the Custom Generator.

Please let me know and I'll adjust the CG if necessary.

**Comment by evgeniyshay** [comment]
I know that this is not make sense, but themeforest reviewers looking for
code patters in themes and maybe have no time to take code to a pieces but
they return theme themes with soft reject. Author can try to explain, but I
am not sure that theme doesn't return with same reject.
That's why this not make sense, but it save the time on review.
Yes you are right and now it is no difference between wordpress.org &
themeforest requirements.

2016-05-19 3:51 GMT+03:00 Juliette <notifications@github.com>:

**Comment by GaryJones** [comment]
> Author can try to explain, but I am not sure that theme doesn't return with same reject.

Then @Stephen-Cronin needs to jump in to educate their reviewers and allow them time to understand what is technically correct. It's not up to TGMPA (or other project) to apply inconsistent or bad security practices just to pass checks.

**Comment by Uranbold** [comment]
Anyone has all Text domain has changed and escaped version for themeforest. No matter how i explained to Reviewer they reject at least once and keep telling theme doesn't need 2 different text domain.

**Comment by Stephen-Cronin** [comment]
Sorry missed this the first time around.

@Uranbold - Having a separate text domain for TGMPA is fine for ThemeForest. If you are soft rejected for that reason, then when you're resubmitting, just add a note for the reviewer to check with me. Sorry for any confusion.

@evgeniyshay - Hmm, I'll look into that. Which account were you using on ThemeForest? I'd like to look at a real eg. Maybe [lodge a ticket](https://help.market.envato.com/hc/en-us/requests/new) with some details and say I asked for it to be directed to me. Thanks.

**Comment by Uranbold** [comment]
@Stephen-Cronin Thanks for clarification.

But Downloading this plugin for WP.org is fine solution. I think TGM Generator for Themeforest is working little bit wrong.

**Comment by Stephen-Cronin** [comment]
@Uranbold - yep, if you use the wp.org version then it will be accepted on TF without any problem. But the TF version should also be accepted! 

With the specific issue of text domains, we do allow a separate one for TGMPA. If you use it, then you can use the translations that come with TGMPA. If you use the wp.org version, those translations won't work. So if a reviewer rejects a theme for that reason, please resubmit and ask to check with me. :)

Or you can also [lodge a ticket](https://help.market.envato.com/hc/en-us/requests/new) with some details (asking for it to be directed to me) and I can look into that specific case. :)
